import type { BuiltInExercise } from '../domain/exercise-catalog';

/**
 * Built-in exercise catalog (ADR-P015 + ADR-P017, `exercise-catalog@0.2.0`).
 *
 * AUTHORED, versioned in-repo reference data — small and representative for
 * v1, NOT exhaustive. Each entry declares the movement patterns it involves,
 * drawn from the iCoach engine's excluded-movement vocabulary
 * (`features/icoach/domain/restrictions.ts`), so a `TrainingPlan.excludedMovements`
 * list can flag it. Movement classification follows standard exercise-science
 * joint/loading patterns; no external dataset, no licensing, no network.
 *
 * `key`s are stable slugs (durable identity for a future `exercises` catalog
 * seed with `createdBy = null`). No schema change is introduced by this file.
 */
export const BUILT_IN_EXERCISES: readonly BuiltInExercise[] = [
  // ── Squat pattern ────────────────────────────────────────────────────────
  {
    id: '75156ac5-8fd5-5e08-a9e8-d6ceb300e4ea',
    key: 'exercise.back_squat',
    name: 'Back squat',
    category: 'STRENGTH',
    muscleGroup: 'quadriceps',
    trainingPatterns: ['SQUAT'],
    movementPatterns: ['deep_squat', 'max_effort_lifts', 'valsalva_heavy_lifts'],
    equipment: ['barbell'],
    bodyAreas: ['knee', 'hip', 'lower_back'],
  },
  {
    id: '6481d435-c659-5a84-b9c9-ebf725751bc7',
    key: 'exercise.front_squat',
    name: 'Front squat',
    category: 'STRENGTH',
    muscleGroup: 'quadriceps',
    trainingPatterns: ['SQUAT'],
    movementPatterns: ['deep_squat', 'front_rack_loading'],
    equipment: ['barbell'],
    bodyAreas: ['knee', 'hip', 'wrist'],
  },
  {
    id: '57195b26-88bc-58e8-a694-9862a1e9e87d',
    key: 'exercise.goblet_squat',
    name: 'Goblet squat',
    category: 'STRENGTH',
    muscleGroup: 'quadriceps',
    trainingPatterns: ['SQUAT'],
    movementPatterns: ['deep_squat'],
    equipment: ['dumbbell', 'kettlebell'],
    bodyAreas: ['knee', 'hip'],
  },
  {
    id: 'a3996daf-487b-58ff-8bab-c612d0443cc1',
    key: 'exercise.walking_lunge',
    name: 'Walking lunge',
    category: 'STRENGTH',
    muscleGroup: 'glutes',
    trainingPatterns: ['SQUAT'],
    movementPatterns: ['lunge'],
    equipment: ['dumbbell', 'bodyweight', 'none'],
    bodyAreas: ['knee', 'hip'],
  },
  // ── Hinge pattern ──────────────────────────────────────────────────────────
  {
    id: 'b8d85de3-ae67-51ff-9aae-7f1786df0bdf',
    key: 'exercise.deadlift',
    name: 'Conventional deadlift',
    category: 'STRENGTH',
    muscleGroup: 'hamstrings',
    trainingPatterns: ['HINGE'],
    movementPatterns: [
      'heavy_hinge',
      'loaded_spinal_flexion',
      'max_effort_lifts',
      'valsalva_heavy_lifts',
    ],
    equipment: ['barbell'],
    bodyAreas: ['lower_back', 'hip'],
  },
  {
    id: '1b69062e-f99d-5f22-b7c9-0f689a1c0316',
    key: 'exercise.romanian_deadlift',
    name: 'Romanian deadlift',
    category: 'STRENGTH',
    muscleGroup: 'hamstrings',
    trainingPatterns: ['HINGE'],
    movementPatterns: ['heavy_hinge'],
    equipment: ['barbell', 'dumbbell'],
    bodyAreas: ['lower_back', 'hip'],
  },
  {
    id: '8495e900-0a5f-5a83-8923-990bf32b2545',
    key: 'exercise.good_morning',
    name: 'Good morning',
    category: 'STRENGTH',
    muscleGroup: 'hamstrings',
    trainingPatterns: ['HINGE'],
    movementPatterns: ['good_morning', 'heavy_hinge', 'loaded_spinal_flexion'],
    equipment: ['barbell'],
    bodyAreas: ['lower_back'],
  },
  // ── Press pattern ──────────────────────────────────────────────────────────
  {
    id: 'd1ceae37-cdef-59d4-bcd2-9edbdd091aa0',
    key: 'exercise.overhead_press',
    name: 'Overhead press',
    category: 'STRENGTH',
    muscleGroup: 'shoulders',
    trainingPatterns: ['VERTICAL_PUSH'],
    movementPatterns: ['overhead_press', 'heavy_pressing', 'max_effort_lifts'],
    equipment: ['barbell'],
    bodyAreas: ['shoulder', 'wrist'],
  },
  {
    id: 'd60f25e2-3035-5adb-8a15-ffe2511864c9',
    key: 'exercise.bench_press',
    name: 'Bench press',
    category: 'STRENGTH',
    muscleGroup: 'chest',
    trainingPatterns: ['HORIZONTAL_PUSH'],
    movementPatterns: ['heavy_pressing', 'max_effort_lifts', 'valsalva_heavy_lifts'],
    equipment: ['barbell'],
    bodyAreas: ['shoulder', 'wrist', 'elbow'],
  },
  {
    id: 'de86bea6-a71f-5bd2-8b2e-18137c4f959e',
    key: 'exercise.dips',
    name: 'Parallel-bar dips',
    category: 'BODYWEIGHT',
    muscleGroup: 'triceps',
    trainingPatterns: ['HORIZONTAL_PUSH'],
    movementPatterns: ['dips', 'heavy_pressing'],
    equipment: ['bodyweight', 'none'],
    bodyAreas: ['shoulder', 'elbow'],
  },
  {
    id: '8081efeb-460a-54b7-a7b6-ad09208e279c',
    key: 'exercise.skull_crusher',
    name: 'Skull crusher',
    category: 'STRENGTH',
    muscleGroup: 'triceps',
    trainingPatterns: ['HORIZONTAL_PUSH'],
    movementPatterns: ['skull_crushers'],
    equipment: ['barbell', 'dumbbell'],
    bodyAreas: ['elbow'],
  },
  // ── Carry / core ───────────────────────────────────────────────────────────
  {
    id: '0b7bc277-5e48-526f-955b-8dcca4c3e9a5',
    key: 'exercise.farmers_carry',
    name: "Farmer's carry",
    category: 'STRENGTH',
    muscleGroup: 'full_body',
    trainingPatterns: ['CARRY'],
    movementPatterns: ['loaded_carries'],
    equipment: ['dumbbell', 'kettlebell'],
    bodyAreas: ['neck', 'back'],
  },
  {
    id: 'd7ad9c4d-9f86-5bfe-af50-cd3c55bb28ac',
    key: 'exercise.plank',
    name: 'Front plank',
    category: 'BODYWEIGHT',
    muscleGroup: 'core',
    trainingPatterns: ['CORE'],
    movementPatterns: [],
    equipment: ['bodyweight', 'none'],
    bodyAreas: ['core'],
  },
  {
    id: '51015a86-3b92-5966-9ceb-c204cc544863',
    key: 'exercise.seated_cable_row',
    name: 'Seated cable row',
    category: 'STRENGTH',
    muscleGroup: 'back',
    trainingPatterns: ['HORIZONTAL_PULL'],
    movementPatterns: [],
    equipment: ['cable', 'machine'],
    bodyAreas: ['back'],
  },
  // ── Conditioning ───────────────────────────────────────────────────────────
  {
    id: '41c3faf2-af64-5a17-acee-ddb5ae3e88a2',
    key: 'exercise.box_jump',
    name: 'Box jump',
    category: 'BODYWEIGHT',
    muscleGroup: 'quadriceps',
    trainingPatterns: ['SQUAT', 'CONDITIONING'],
    movementPatterns: ['jumping', 'high_impact_cardio'],
    equipment: ['bodyweight', 'none'],
    bodyAreas: ['knee', 'ankle'],
  },
  {
    id: '8a0cb656-ebf9-5605-8368-3e8f24dbd840',
    key: 'exercise.steady_run',
    name: 'Steady-state run',
    category: 'CARDIO',
    muscleGroup: 'full_body',
    trainingPatterns: ['CONDITIONING'],
    movementPatterns: ['running', 'high_impact_cardio'],
    equipment: ['none'],
    bodyAreas: ['knee', 'ankle'],
  },
  {
    id: 'b0196c65-0443-5f5d-b958-27a9be382fac',
    key: 'exercise.sprint_intervals',
    name: 'Sprint intervals',
    category: 'CARDIO',
    muscleGroup: 'full_body',
    trainingPatterns: ['CONDITIONING'],
    movementPatterns: ['sprinting', 'running', 'high_impact_cardio'],
    equipment: ['none'],
    bodyAreas: ['hip', 'knee', 'ankle'],
  },
  // â”€â”€ Public-v1 balanced routine coverage (ADR-P017 Phase 21 Slice 5C) â”€â”€
  {
    id: '3a292c26-269a-5262-8494-f7be22a206e5',
    key: 'exercise.bodyweight_squat',
    name: 'Bodyweight squat',
    category: 'BODYWEIGHT',
    muscleGroup: 'quadriceps',
    trainingPatterns: ['SQUAT'],
    movementPatterns: ['deep_squat'],
    equipment: ['bodyweight', 'none'],
    bodyAreas: ['knee', 'hip'],
  },
  {
    id: '96e1ee0b-012b-54b1-939c-6941cec13d5d',
    key: 'exercise.glute_bridge',
    name: 'Glute bridge',
    category: 'BODYWEIGHT',
    muscleGroup: 'glutes',
    trainingPatterns: ['HINGE'],
    movementPatterns: ['bridging'],
    equipment: ['bodyweight', 'none'],
    bodyAreas: ['hip', 'lower_back'],
  },
  {
    id: '43cdab00-f9c0-5af6-ab44-c2fbbaf11913',
    key: 'exercise.push_up',
    name: 'Push-up',
    category: 'BODYWEIGHT',
    muscleGroup: 'chest',
    trainingPatterns: ['HORIZONTAL_PUSH'],
    movementPatterns: ['heavy_pressing'],
    equipment: ['bodyweight', 'none'],
    bodyAreas: ['shoulder', 'wrist', 'elbow', 'core'],
  },
  {
    id: '7fb16a06-3c04-5807-b99b-75c570b38771',
    key: 'exercise.prone_snow_angel',
    name: 'Prone snow angel',
    category: 'BODYWEIGHT',
    muscleGroup: 'back',
    trainingPatterns: ['UPPER_BACK'],
    movementPatterns: [],
    equipment: ['bodyweight', 'none'],
    bodyAreas: ['back', 'shoulder'],
  },
  {
    id: '2e934ea8-6f2b-5a2a-aba6-9e871334be75',
    key: 'exercise.dumbbell_floor_press',
    name: 'Dumbbell floor press',
    category: 'STRENGTH',
    muscleGroup: 'chest',
    trainingPatterns: ['HORIZONTAL_PUSH'],
    movementPatterns: ['heavy_pressing'],
    equipment: ['dumbbell'],
    bodyAreas: ['shoulder', 'wrist', 'elbow'],
  },
  {
    id: '71ec3f6d-878f-5454-b9d5-b4f29b8e5508',
    key: 'exercise.one_arm_dumbbell_row',
    name: 'One-arm dumbbell row',
    category: 'STRENGTH',
    muscleGroup: 'back',
    trainingPatterns: ['HORIZONTAL_PULL'],
    movementPatterns: [],
    equipment: ['dumbbell'],
    bodyAreas: ['back', 'shoulder'],
  },
  {
    id: 'e6be0757-72c0-5516-a3a3-2a61d9005a06',
    key: 'exercise.kettlebell_deadlift',
    name: 'Kettlebell deadlift',
    category: 'STRENGTH',
    muscleGroup: 'hamstrings',
    trainingPatterns: ['HINGE'],
    movementPatterns: ['heavy_hinge'],
    equipment: ['kettlebell'],
    bodyAreas: ['lower_back', 'hip'],
  },
  {
    id: 'f345443a-5cb0-5991-8a99-704b0720014a',
    key: 'exercise.kettlebell_overhead_press',
    name: 'Kettlebell overhead press',
    category: 'STRENGTH',
    muscleGroup: 'shoulders',
    trainingPatterns: ['VERTICAL_PUSH'],
    movementPatterns: ['overhead_press', 'heavy_pressing'],
    equipment: ['kettlebell'],
    bodyAreas: ['shoulder', 'wrist'],
  },
  {
    id: 'c273538e-6198-589e-9a9b-c9a118662b1c',
    key: 'exercise.kettlebell_row',
    name: 'Kettlebell row',
    category: 'STRENGTH',
    muscleGroup: 'back',
    trainingPatterns: ['HORIZONTAL_PULL'],
    movementPatterns: [],
    equipment: ['kettlebell'],
    bodyAreas: ['back', 'shoulder'],
  },
  {
    id: 'cd5df461-d632-59f1-9ce6-5002657c3629',
    key: 'exercise.bent_over_barbell_row',
    name: 'Bent-over barbell row',
    category: 'STRENGTH',
    muscleGroup: 'back',
    trainingPatterns: ['HORIZONTAL_PULL', 'HINGE'],
    movementPatterns: ['heavy_hinge', 'loaded_spinal_flexion'],
    equipment: ['barbell'],
    bodyAreas: ['back', 'lower_back', 'hip'],
  },
  {
    id: 'a7b7d07c-e38c-56f8-8f4e-9cfa580abf82',
    key: 'exercise.machine_chest_press',
    name: 'Machine chest press',
    category: 'STRENGTH',
    muscleGroup: 'chest',
    trainingPatterns: ['HORIZONTAL_PUSH'],
    movementPatterns: ['heavy_pressing'],
    equipment: ['machine'],
    bodyAreas: ['shoulder', 'elbow'],
  },
  {
    id: '22346d44-7111-5d48-83bb-10209c9717c3',
    key: 'exercise.lat_pulldown',
    name: 'Lat pulldown',
    category: 'STRENGTH',
    muscleGroup: 'back',
    trainingPatterns: ['VERTICAL_PULL'],
    movementPatterns: [],
    equipment: ['cable', 'machine'],
    bodyAreas: ['back', 'shoulder', 'elbow'],
  },
  {
    id: '4b4df18d-e6cb-551f-b114-06aba6109794',
    key: 'exercise.leg_press',
    name: 'Leg press',
    category: 'STRENGTH',
    muscleGroup: 'quadriceps',
    trainingPatterns: ['SQUAT'],
    movementPatterns: ['deep_squat'],
    equipment: ['machine'],
    bodyAreas: ['knee', 'hip'],
  },
  {
    id: '725c83c9-9de8-5468-8c62-b4125a5f763b',
    key: 'exercise.cable_pull_through',
    name: 'Cable pull-through',
    category: 'STRENGTH',
    muscleGroup: 'glutes',
    trainingPatterns: ['HINGE'],
    movementPatterns: ['heavy_hinge'],
    equipment: ['cable'],
    bodyAreas: ['hip', 'lower_back'],
  },
  {
    id: 'fd018124-d988-545e-86aa-6eb2d3ec2762',
    key: 'exercise.brisk_walk',
    name: 'Brisk walk',
    category: 'CARDIO',
    muscleGroup: 'full_body',
    trainingPatterns: ['CONDITIONING'],
    movementPatterns: [],
    equipment: ['none'],
    bodyAreas: ['full_body'],
  },
  {
    id: '90c0f87b-983b-5591-b606-f6acf25b6c14',
    key: 'exercise.cat_cow',
    name: 'Cat-cow mobility',
    category: 'FLEXIBILITY',
    muscleGroup: 'core',
    trainingPatterns: ['MOBILITY'],
    movementPatterns: [],
    equipment: ['bodyweight', 'none'],
    bodyAreas: ['back', 'core'],
  },
];

const byKey: ReadonlyMap<string, BuiltInExercise> = new Map(
  BUILT_IN_EXERCISES.map((e) => [e.key, e]),
);
const byId: ReadonlyMap<string, BuiltInExercise> = new Map(
  BUILT_IN_EXERCISES.map((e) => [e.id, e]),
);

/** Built-in exercise by stable key, or undefined (custom/unmapped). */
export function getBuiltInExercise(key: string): BuiltInExercise | undefined {
  return byKey.get(key);
}

/** Built-in exercise by durable UUID id, or undefined (custom/unmapped). */
export function getBuiltInExerciseById(id: string): BuiltInExercise | undefined {
  return byId.get(id);
}

/** All built-in exercises (stable order). */
export function listBuiltInExercises(): readonly BuiltInExercise[] {
  return BUILT_IN_EXERCISES;
}

/** True iff the key names a built-in (mapped) exercise. */
export function isBuiltInExercise(key: string): boolean {
  return byKey.has(key);
}
