/** Spanish presentation labels keyed by the catalog's stable exercise identity. */
export const SPANISH_EXERCISE_NAMES: Readonly<Record<string, string>> = {
  'exercise.back_squat': 'Sentadilla trasera',
  'exercise.front_squat': 'Sentadilla frontal',
  'exercise.goblet_squat': 'Sentadilla goblet',
  'exercise.walking_lunge': 'Zancada caminando',
  'exercise.deadlift': 'Peso muerto convencional',
  'exercise.romanian_deadlift': 'Peso muerto rumano',
  'exercise.good_morning': 'Buenos días',
  'exercise.overhead_press': 'Press sobre la cabeza',
  'exercise.bench_press': 'Press de banca',
  'exercise.dips': 'Fondos en barras paralelas',
  'exercise.skull_crusher': 'Extensión de tríceps acostado',
  'exercise.farmers_carry': 'Caminata del granjero',
  'exercise.plank': 'Plancha frontal',
  'exercise.seated_cable_row': 'Remo sentado en polea',
  'exercise.box_jump': 'Salto al cajón',
  'exercise.steady_run': 'Carrera a ritmo constante',
  'exercise.sprint_intervals': 'Intervalos de velocidad',
  'exercise.bodyweight_squat': 'Sentadilla con peso corporal',
  'exercise.glute_bridge': 'Puente de glúteos',
  'exercise.push_up': 'Flexión de brazos',
  'exercise.prone_snow_angel': 'Ángel de nieve boca abajo',
  'exercise.dumbbell_floor_press': 'Press con mancuernas en el suelo',
  'exercise.one_arm_dumbbell_row': 'Remo con mancuerna a un brazo',
  'exercise.kettlebell_deadlift': 'Peso muerto con pesa rusa',
  'exercise.kettlebell_overhead_press': 'Press sobre la cabeza con pesa rusa',
  'exercise.kettlebell_row': 'Remo con pesa rusa',
  'exercise.bent_over_barbell_row': 'Remo inclinado con barra',
  'exercise.machine_chest_press': 'Press de pecho en máquina',
  'exercise.lat_pulldown': 'Jalón al pecho',
  'exercise.leg_press': 'Prensa de piernas',
  'exercise.cable_pull_through': 'Pull-through en polea',
  'exercise.brisk_walk': 'Caminata rápida',
  'exercise.cat_cow': 'Movilidad gato-vaca',
};
