export const en = {
  'language.title': 'Language',
  'language.description': 'Choose the language used by AppFitness.',
  'language.system': 'Device language',
  'language.english': 'English',
  'language.spanish': 'Spanish',
  'language.saveError': 'Language preference could not be saved. Try again.',
  'auth.screenTitle': 'Sign in',
  'auth.subtitle': 'Sign in to continue.',
  'auth.email': 'Email',
  'auth.username': 'Username',
  'auth.password': 'Password',
  'auth.signIn': 'Sign in',
  'auth.register': 'Register',
  'auth.useExistingAccount': 'Use existing account',
  'auth.createAccount': 'Create a local account',
  'auth.switchMode': 'Switch authentication mode',
  'auth.errorTitle': 'Sign-in error',
  'auth.errorMessage': 'Authentication failed. Check your credentials and connection.',
  'progress.measurements.accessibility': 'Record body measurements',
  'progress.measurements.title': 'Record measurements',
  'progress.measurements.date': 'Date',
  'progress.measurements.waist': 'Waist (cm, optional)',
  'progress.measurements.waistPlaceholder': 'e.g. 82',
  'progress.measurements.hip': 'Hip (cm, optional)',
  'progress.measurements.hipPlaceholder': 'e.g. 96',
  'progress.measurements.chest': 'Chest (cm, optional)',
  'progress.measurements.chestPlaceholder': 'e.g. 100',
  'progress.measurements.bodyFat': 'Body fat (%, optional)',
  'progress.measurements.bodyFatPlaceholder': 'e.g. 18',
  'progress.measurements.muscleMass': 'Muscle mass (kg, optional)',
  'progress.measurements.muscleMassPlaceholder': 'e.g. 35',
  'progress.measurements.muscleMassRange': 'Enter muscle mass greater than 0 and at most 300 kg',
  'progress.measurements.atLeastOne': 'Enter at least one body measurement',
  'progress.measurements.notes': 'Notes (optional)',
  'progress.measurements.notesPlaceholder': 'Anything worth remembering',
  'progress.measurements.save': 'Save measurements',
  'progress.measurements.saveAccessibility': 'Save body measurements',
  'progress.trends.muscleMass': 'Muscle mass',
  'nutrition.plan.routeTitle': 'Meal plan',
  'nutrition.plan.title': '15-day meal plan',
  'nutrition.plan.subtitle':
    'A deterministic routine built from your iCoach targets and the local food catalog.',
  'nutrition.plan.logToday': "Log today's food",
  'nutrition.plan.logTodayAccessibility': 'Log the food you ate today',
  'nutrition.plan.loading': 'Loading…',
  'nutrition.plan.loadingAccessibility': 'Loading meal plan',
  'nutrition.plan.unavailable': 'Meal plan unavailable',
  'nutrition.plan.errorMessage': 'Your meal plan could not be built right now. Try again later.',
  'nutrition.plan.day': 'Day',
  'nutrition.plan.showDay': 'Show day',
  'nutrition.plan.breakfast': 'Breakfast',
  'nutrition.plan.lunch': 'Lunch',
  'nutrition.plan.dinner': 'Dinner',
  'nutrition.plan.snack': 'Snack',
  'nutrition.plan.meal': 'meal',
  'nutrition.plan.mealTotal': 'Meal total',
  'nutrition.plan.dayTotalsAccessibility': 'Day totals versus targets',
  'nutrition.plan.dayTotalTarget': 'Day total vs target',
  'nutrition.plan.calories': 'Calories',
  'nutrition.plan.protein': 'Protein',
  'nutrition.plan.carbs': 'Carbs',
  'nutrition.plan.fat': 'Fat',
  'nutrition.plan.targetSummary': 'target',
  'nutrition.plan.safeMinimumTitle': 'Safe minimum applied',
  'nutrition.plan.safeMinimumMessage':
    'The calorie target was raised to the safe minimum used by AppFitness.',
  'nutrition.plan.disclaimer':
    'These suggestions are general fitness guidance based on your profile and goal, not medical or dietary advice. Consult a qualified professional before making significant changes.',
  'nutrition.plan.preferencesAccessibility': 'Applied dietary preferences',
  'nutrition.plan.preferencesTitle': 'Your dietary preferences shaped this plan',
  'nutrition.plan.avoidedCategories': 'Avoided categories',
  'nutrition.plan.excludedFoods': 'Excluded foods',
  'nutrition.plan.preferencesExplanation':
    'Allergies and preferences deterministically remove foods before selection, so the plan reflects them. This is not medical advice.',
  'nutrition.targets.title': 'Nutrition targets',
  'nutrition.targets.subtitle':
    'Your daily calorie and macronutrient targets from your iCoach assessment.',
  'nutrition.targets.loadingAccessibility': 'Loading nutrition targets',
  'nutrition.targets.unavailable': 'Nutrition unavailable',
  'nutrition.targets.errorMessage': 'Your nutrition targets could not be loaded right now.',
  'nutrition.targets.calorieAccessibility': 'Daily calorie target',
  'nutrition.targets.dailyCalories': 'Daily calories',
  'nutrition.targets.macrosAccessibility': 'Macronutrient breakdown',
  'nutrition.targets.macros': 'Macros',
  'nutrition.targets.viewPlan': '15-day meal plan',
  'nutrition.targets.viewPlanAccessibility': 'View your 15-day meal plan',
  'nutrition.targets.maintenancePrefix': 'Calories are set at your maintenance level for',
  'nutrition.targets.adjustmentPrefix': 'Calories are set',
  'nutrition.targets.below': 'below',
  'nutrition.targets.above': 'above',
  'nutrition.targets.adjustmentSuffix': 'maintenance to support',
  'nutrition.goal.fatLoss': 'fat loss',
  'nutrition.goal.muscleGain': 'muscle gain',
  'nutrition.goal.recomposition': 'body recomposition',
  'nutrition.goal.strength': 'strength',
  'nutrition.goal.endurance': 'endurance',
  'nutrition.goal.generalHealth': 'general wellness',
  'nutrition.goal.rehabilitation': 'recovery',
  'nutrition.goal.maintenance': 'maintenance',
  'nutrition.preferences.title': 'Dietary preferences & allergies',
  'nutrition.preferences.subtitle':
    'Tell iCoach what to avoid. Allergies and preferences shape your meal suggestions and show advisory warnings without blocking your choices. Entries are saved on your device first and sync to your account later.',
  'nutrition.preferences.errorTitle': 'Something went wrong',
  'nutrition.preferences.errorMessage': 'Your dietary preferences could not be loaded right now.',
  'nutrition.preferences.addAccessibility': 'Add an exclusion',
  'nutrition.preferences.addTitle': 'Add an exclusion',
  'nutrition.preferences.what': 'What are you excluding?',
  'nutrition.preferences.categoryChoice': 'A category',
  'nutrition.preferences.foodChoice': 'A specific food',
  'nutrition.preferences.why': 'Why?',
  'nutrition.preferences.allergy': 'Allergy / sensitivity',
  'nutrition.preferences.preference': 'Preference / dislike',
  'nutrition.preferences.category': 'Category',
  'nutrition.preferences.findFood': 'Find a food',
  'nutrition.preferences.searchAccessibility': 'Search foods to exclude',
  'nutrition.preferences.searchPlaceholder': 'Search foods…',
  'nutrition.preferences.selected': 'Selected',
  'nutrition.preferences.noteAccessibility': 'Optional note',
  'nutrition.preferences.notePlaceholder': 'Optional note (encrypted on your device)',
  'nutrition.preferences.addButton': 'Add exclusion',
  'nutrition.preferences.listTitle': 'Your exclusions',
  'nutrition.preferences.loadingAccessibility': 'Loading dietary preferences',
  'nutrition.preferences.empty': 'No exclusions yet.',
  'nutrition.preferences.exclusion': 'Exclusion',
  'nutrition.preferences.categorySuffix': 'category',
  'nutrition.preferences.foodSuffix': 'food',
  'nutrition.preferences.noteSaved': 'note saved',
  'nutrition.preferences.remove': 'Remove',
  'nutrition.preferences.removeAccessibility': 'Remove exclusion',
  'nutrition.log.title': 'Food log',
  'nutrition.log.subtitle':
    'Log what you eat today. Saved on your device first, synced when online.',
  'nutrition.log.syncingTitle': 'Syncing',
  'nutrition.log.syncingMessage': 'Sending your food log.',
  'nutrition.log.offlineTitle': 'Offline',
  'nutrition.log.offlineMessage': 'Your log is saved on this device and will sync later.',
  'nutrition.log.actionTitle': 'Action needed',
  'nutrition.log.actionMessageOne':
    'item cannot sync because the food is not available on the server. Remove and re-add it to continue.',
  'nutrition.log.actionMessageMany':
    'items cannot sync because the food is not available on the server. Remove and re-add them to continue.',
  'nutrition.log.syncErrorTitle': 'Sync needs attention',
  'nutrition.log.syncErrorMessage': 'Your log is saved locally. We will try again.',
  'nutrition.log.pendingTitle': 'Changes pending',
  'nutrition.log.pendingMessageOne': 'change is waiting to sync.',
  'nutrition.log.pendingMessageMany': 'changes are waiting to sync.',
  'nutrition.log.syncedTitle': 'Log up to date',
  'nutrition.log.syncedMessage': 'Your food log is saved and synced.',
  'nutrition.log.actionAccessibility': 'Sync action required',
  'nutrition.log.pendingAccessibility': 'Sync pending',
  'nutrition.log.actionShort': 'Action needed',
  'nutrition.log.pendingShort': 'Pending sync',
  'nutrition.log.servings': 'servings',
  'nutrition.log.remove': 'Remove',
  'nutrition.log.removeAccessibility': 'Remove',
  'nutrition.log.entries': 'entries',
  'nutrition.log.totalsAccessibility': 'Daily totals from your logged entries',
  'nutrition.log.totals': "Today's totals",
  'nutrition.log.fiber': 'Fiber',
  'nutrition.log.loadingAccessibility': 'Loading food log',
  'nutrition.log.unavailable': 'Food log unavailable',
  'nutrition.log.errorMessage': 'Your food log could not be loaded right now. Please try again.',
  'nutrition.log.emptyAccessibility': 'No food logged yet',
  'nutrition.log.emptyTitle': 'Nothing logged yet',
  'nutrition.log.emptyMessage':
    'Search the catalog above and add your first food to see your daily totals.',
  'nutrition.log.syncNow': 'Sync now',
  'nutrition.log.syncNowAccessibility': 'Sync your food log now',
  'nutrition.log.addAccessibility': 'Add a food to your log',
  'nutrition.log.addTitle': 'Add food',
  'nutrition.log.mealAccessibility': 'Meal',
  'nutrition.log.searchAccessibility': 'Search foods',
  'nutrition.log.searchPlaceholder': 'Search foods (e.g. chicken, oats)',
  'nutrition.log.choose': 'Choose',
  'nutrition.log.noResults': 'No foods match that search.',
  'nutrition.log.oneServing': '1 serving',
  'nutrition.log.addButton': 'Add to log',
  'nutrition.log.logAccessibility': 'Log',
  'nutrition.log.decreaseServings': 'Decrease servings',
  'nutrition.log.increaseServings': 'Increase servings',
  'nutrition.warning.allergyTitle': 'Heads up — this matches an allergy or sensitivity',
  'nutrition.warning.preferenceTitle': 'This is on your avoid list',
  'nutrition.warning.catalogReason': 'a food you chose to avoid',
  'nutrition.warning.matches': 'matches',
  'nutrition.warning.join': 'and',
  'nutrition.warning.allergyAdvice':
    'You can still log it, but double-check that it is safe for you. This is not emergency medical advice.',
  'nutrition.warning.preferenceAdvice':
    'in your dietary preferences. You can still log it if you would like.',
  'nutrition.avoid.nuts': 'Nuts',
  'nutrition.avoid.shellfish': 'Shellfish',
  'nutrition.avoid.gluten': 'Gluten',
  'nutrition.avoid.lactose': 'Lactose / dairy',
  'nutrition.avoid.sodium': 'High sodium',
  'nutrition.avoid.purine': 'High purine',
  'nutrition.unit.g': 'g',
  'nutrition.unit.ml': 'ml',
  'nutrition.unit.piece': 'piece',
  'nutrition.unit.cup': 'cup',
  'nutrition.unit.tbsp': 'tbsp',
  'nutrition.unit.tsp': 'tsp',
  'nutrition.unit.slice': 'slice',
  'nutrition.gap.planAccessibility': 'Meal plan needs more data',
  'nutrition.gap.targetsAccessibility': 'Nutrition needs more data',
  'nutrition.gap.title': 'Finish your baseline first',
  'nutrition.gap.description':
    'Nutrition targets need your profile (birth date and height) and a recent weight.',
  'nutrition.gap.planSuffix': 'Your 15-day meal plan builds on those targets.',
  'nutrition.gap.profileTitle': 'Add your profile details',
  'nutrition.gap.profileButton': 'Create or edit profile',
  'nutrition.gap.profileAccessibility': 'Create or edit your profile',
  'nutrition.gap.weightTitle': 'Record a weight',
  'nutrition.gap.weightButton': 'Record weight',
  'nutrition.gap.weightAccessibility': 'Record your body weight',
  'nutrition.gap.dashboardButton': 'Go to dashboard',
  'nutrition.gap.dashboardAccessibility': 'Go to the dashboard to finish your baseline',
  'nutrition.gap.profileDetail': 'A profile is required.',
  'nutrition.gap.birthDateDetail': 'Your birth date is required.',
  'nutrition.gap.heightDetail': 'Your height is required.',
  'nutrition.gap.weightDetail': 'A recent weight is required.',
  'nutrition.gap.wellnessNotice':
    'AppFitness uses self-entered wellness data for these suggestions. It does not request diagnoses, prescriptions, doctor notes, or professional medical restrictions.',
} as const;

export type TranslationKey = keyof typeof en;
