export const en = {
  'language.title': 'Language',
  'language.description': 'Choose the language used by AppFitness.',
  'language.system': 'Device language',
  'language.english': 'English',
  'language.spanish': 'Spanish',
  'language.saveError': 'Language preference could not be saved. Try again.',
  'auth.screenTitle': 'Sign in',
  'auth.subtitle': 'Sign in to continue.',
  'auth.email': 'Email',
  'auth.username': 'Username',
  'auth.password': 'Password',
  'auth.signIn': 'Sign in',
  'auth.register': 'Register',
  'auth.useExistingAccount': 'Use existing account',
  'auth.createAccount': 'Create a local account',
  'auth.switchMode': 'Switch authentication mode',
  'auth.errorTitle': 'Sign-in error',
  'auth.errorMessage': 'Authentication failed. Check your credentials and connection.',
  'profile.loading': 'Loading…',
  'profile.loadingAccessibility': 'Loading profile',
  'profile.routeTitle': 'Profile',
  'profile.createTitle': 'Create your profile',
  'profile.editTitle': 'Edit profile',
  'profile.subtitle':
    'Saved on your device first, then synced. Required fields unlock your iCoach assessment.',
  'profile.errorTitle': 'Couldn’t save',
  'profile.errorMessage': 'Your profile could not be saved right now. Try again.',
  'profile.birthDate': 'Birth date',
  'profile.heightCm': 'Height (cm)',
  'profile.gender': 'Gender',
  'profile.gender.male': 'Male',
  'profile.gender.female': 'Female',
  'profile.gender.other': 'Other',
  'profile.gender.undisclosed': 'Prefer not to say',
  'profile.fitnessLevel': 'Fitness level',
  'profile.fitness.beginner': 'Beginner',
  'profile.fitness.intermediate': 'Intermediate',
  'profile.fitness.advanced': 'Advanced',
  'profile.activityLevel': 'Activity level',
  'profile.activity.sedentary': 'Sedentary',
  'profile.activity.light': 'Light',
  'profile.activity.moderate': 'Moderate',
  'profile.activity.active': 'Active',
  'profile.activity.veryActive': 'Very active',
  'profile.yearsTraining': 'Years training',
  'profile.trainingDaysPerWeek': 'Training days / week',
  'profile.sessionDurationMins': 'Session length (min)',
  'profile.sleepHoursBaseline': 'Typical sleep (hours)',
  'profile.stressLevelBaseline': 'Typical stress (1–5)',
  'profile.occupation': 'Occupation',
  'profile.equipment': 'Equipment (comma separated)',
  'profile.save': 'Save profile',
  'profile.validation.dateFormat': 'Use YYYY-MM-DD',
  'profile.validation.validDate': 'Enter a valid date',
  'profile.validation.greaterThanZero': 'Must be greater than 0',
  'profile.validation.tooLarge': 'Too large',
  'profile.validation.cannotBeNegative': 'Cannot be negative',
  'profile.validation.maxSeven': 'Max 7',
  'profile.validation.scaleOneToFive': 'Scale 1–5',
  'goal.loading': 'Loading…',
  'goal.loadingAccessibility': 'Loading goal',
  'goal.routeTitle': 'Goal',
  'goal.createTitle': 'Set your goal',
  'goal.editTitle': 'Edit goal',
  'goal.subtitle':
    'Saved on your device first, then synced automatically. Your goal personalizes calorie and training adjustments.',
  'goal.errorTitle': 'Couldn’t save',
  'goal.errorMessage': 'Your goal could not be saved right now. Try again.',
  'goal.conflictTitle': 'Sync conflict',
  'goal.conflictMessage':
    'This goal has a sync conflict. Saving records a fresh goal on this device and queues it for sync again.',
  'goal.pendingTitle': 'Saved on this device',
  'goal.pendingMessage': 'Your latest goal is saved locally and waiting to sync.',
  'goal.typeLabel': 'Goal',
  'goal.type.fatLoss': 'Fat loss',
  'goal.type.muscleGain': 'Muscle gain',
  'goal.type.recomposition': 'Recomposition',
  'goal.type.strength': 'Strength',
  'goal.type.endurance': 'Endurance',
  'goal.type.generalHealth': 'General wellness',
  'goal.type.maintenance': 'Maintenance',
  'goal.targetWeightKg': 'Target weight (kg)',
  'goal.targetDate': 'Target date',
  'goal.targetDatePlaceholder': 'YYYY-MM-DD',
  'goal.save': 'Save goal',
  'goal.validation.greaterThanZero': 'Must be greater than 0',
  'goal.validation.tooLarge': 'Too large',
  'goal.validation.dateFormat': 'Use YYYY-MM-DD',
  'goal.validation.validDate': 'Enter a valid date',
  'progress.measurements.accessibility': 'Record body measurements',
  'progress.measurements.title': 'Record measurements',
  'progress.measurements.date': 'Date',
  'progress.measurements.waist': 'Waist (cm, optional)',
  'progress.measurements.waistPlaceholder': 'e.g. 82',
  'progress.measurements.hip': 'Hip (cm, optional)',
  'progress.measurements.hipPlaceholder': 'e.g. 96',
  'progress.measurements.chest': 'Chest (cm, optional)',
  'progress.measurements.chestPlaceholder': 'e.g. 100',
  'progress.measurements.bodyFat': 'Body fat (%, optional)',
  'progress.measurements.bodyFatPlaceholder': 'e.g. 18',
  'progress.measurements.muscleMass': 'Muscle mass (kg, optional)',
  'progress.measurements.muscleMassPlaceholder': 'e.g. 35',
  'progress.measurements.muscleMassRange': 'Enter muscle mass greater than 0 and at most 300 kg',
  'progress.measurements.atLeastOne': 'Enter at least one body measurement',
  'progress.measurements.notes': 'Notes (optional)',
  'progress.measurements.notesPlaceholder': 'Anything worth remembering',
  'progress.measurements.save': 'Save measurements',
  'progress.measurements.saveAccessibility': 'Save body measurements',
  'progress.trends.muscleMass': 'Muscle mass',
  'workout.plan.accessibility': 'Your deterministic iCoach workout plan',
  'workout.plan.routeTitle': 'Workout routines',
  'workout.plan.title': 'Your weekly iCoach plan',
  'workout.plan.subtitle':
    'Built deterministically from your goal, fitness level, schedule, and available equipment.',
  'workout.plan.loading': 'Building your workout plan…',
  'workout.plan.gapTitle': 'Complete your baseline first',
  'workout.plan.gapMessage': 'Your workout plan needs a completed profile and physical assessment.',
  'workout.plan.blockedTitle': 'Workout plan unavailable',
  'workout.plan.blockedMessage':
    'Your current assessment does not allow a workout plan. Review your wellness inputs before continuing.',
  'workout.plan.errorTitle': 'Workout plan needs attention',
  'workout.plan.errorMessage':
    'A complete routine could not be built from the current equipment and limitations.',
  'workout.plan.unsupportedTitle': 'Equipment not recognized',
  'workout.plan.unsupportedMessage':
    'These profile values were not used. Update them to a supported equipment option:',
  'workout.plan.schedule': 'Weekly schedule',
  'workout.plan.sessions': 'Training sessions',
  'workout.plan.progression': 'How to progress',
  'workout.plan.training': 'Training',
  'workout.plan.activeRecovery': 'Active recovery',
  'workout.plan.fullRest': 'Full rest',
  'workout.plan.session': 'Session',
  'workout.plan.fullBody': 'Full body',
  'workout.plan.sets': 'sets',
  'workout.plan.reps': 'reps',
  'workout.plan.seconds': 'seconds',
  'workout.plan.rest': 'rest',
  'workout.plan.targetRpe': 'target RPE',
  'workout.plan.substitutions': 'Substitutions',
  'workout.plan.afterSessions': 'After successful sessions',
  'workout.plan.addLoad': 'increase load by',
  'workout.plan.addRepetitions': 'add repetitions',
  'workout.plan.addDuration': 'add seconds',
  'workout.plan.wellnessNotice':
    'General fitness guidance only. Stop if an exercise causes pain and adapt the plan to your self-declared physical limitations.',
  'workout.day.monday': 'Monday',
  'workout.day.tuesday': 'Tuesday',
  'workout.day.wednesday': 'Wednesday',
  'workout.day.thursday': 'Thursday',
  'workout.day.friday': 'Friday',
  'workout.day.saturday': 'Saturday',
  'workout.day.sunday': 'Sunday',
  'workout.builder.title': 'Workout routines',
  'workout.builder.subtitle':
    'Build reusable routines from built-in and your own custom exercises. Routines are saved on your device first and sync to your account later.',
  'workout.builder.errorTitle': 'Something went wrong',
  'workout.builder.errorMessage': 'Your routines could not be loaded right now. Try again.',
  'workout.builder.createAccessibility': 'Create a routine',
  'workout.builder.createTitle': 'Create a routine',
  'workout.builder.name': 'Routine name',
  'workout.builder.namePlaceholder': 'e.g. Push day',
  'workout.builder.createButton': 'Create routine',
  'workout.builder.yourRoutines': 'Your routines',
  'workout.builder.loading': 'Loading…',
  'workout.builder.loadingAccessibility': 'Loading routines',
  'workout.builder.empty': 'No routines yet.',
  'workout.builder.routineAccessibility': 'Routine:',
  'workout.builder.viewExercises': 'View exercises',
  'workout.builder.hideExercises': 'Hide exercises',
  'workout.builder.viewExercisesAccessibility': 'View exercises for',
  'workout.builder.removeRoutineAccessibility': 'Remove routine',
  'workout.builder.remove': 'Remove',
  'workout.builder.addExercise': 'Add an exercise',
  'workout.builder.newCustomAccessibility': 'New custom exercise',
  'workout.builder.createCustomAccessibility': 'Create a new custom exercise',
  'workout.builder.newExercise': '+ New exercise',
  'workout.builder.builtIn': 'Built-in',
  'workout.builder.myExercises': 'My exercises',
  'workout.builder.customEmpty': 'No custom exercises yet.',
  'workout.builder.addAccessibility': 'Add',
  'workout.builder.routineExerciseEmpty': 'No exercises in this routine yet.',
  'workout.builder.removedExercise': '(removed exercise)',
  'workout.builder.removeFromRoutineAccessibility': 'Remove from routine:',
  'workout.custom.name': 'Name',
  'workout.custom.namePlaceholder': 'e.g. Zercher squat',
  'workout.custom.normalizedAccessibility': 'Name will be saved as',
  'workout.custom.normalizedPrefix': 'Will be saved as',
  'workout.custom.muscleGroup': 'Muscle group',
  'workout.custom.muscleGroupPlaceholder': 'e.g. legs',
  'workout.custom.category': 'Category',
  'workout.custom.categoryStrength': 'Strength',
  'workout.custom.categoryCardio': 'Cardio',
  'workout.custom.categoryFlexibility': 'Flexibility',
  'workout.custom.categoryBodyweight': 'Bodyweight',
  'workout.custom.instructions': 'Instructions (optional)',
  'workout.custom.instructionsPlaceholder': 'How to perform it',
  'workout.custom.required': 'Required',
  'workout.custom.duplicateName': 'You already have a custom exercise with that name.',
  'workout.custom.saveChanges': 'Save changes',
  'workout.custom.addExerciseAccessibility': 'Add custom exercise',
  'workout.custom.addExercise': 'Add exercise',
  'workout.custom.cancel': 'Cancel',
  'workout.custom.noteAccessibility': 'Custom exercise wellness note',
  'workout.custom.note':
    'Custom exercises aren’t checked automatically against your self-declared physical limitations. Review each exercise and stop if it causes pain.',
  'workout.exclusion.accessibility': 'Exercise limitation warning',
  'workout.exclusion.warning': 'May conflict with your current physical limitations',
  'workout.movement.deepSquat': 'deep squat',
  'workout.movement.lunge': 'lunge',
  'workout.movement.jumping': 'jumping',
  'workout.movement.running': 'running',
  'workout.movement.sprinting': 'sprinting',
  'workout.movement.highImpactCardio': 'high-impact cardio',
  'workout.movement.overheadPress': 'overhead press',
  'workout.movement.behindNeckPress': 'behind-the-neck press',
  'workout.movement.dips': 'dips',
  'workout.movement.heavyPressing': 'heavy pressing',
  'workout.movement.frontRackLoading': 'front-rack loading',
  'workout.movement.skullCrushers': 'skull crushers',
  'workout.movement.heavyHinge': 'heavy hip hinge',
  'workout.movement.goodMorning': 'good morning',
  'workout.movement.loadedSpinalFlexion': 'loaded spinal flexion',
  'workout.movement.loadedCarries': 'loaded carries',
  'workout.movement.bridging': 'bridging',
  'workout.movement.maxEffortLifts': 'maximum-effort lifts',
  'workout.movement.valsalvaHeavyLifts': 'heavy lifts with breath holding',
  'workout.library.routeTitle': 'Exercise library',
  'workout.library.title': 'Exercise library',
  'workout.library.subtitle':
    'Create your own exercises to use in routines and workouts. They are saved on your device first and synced to your account later.',
  'workout.library.errorTitle': 'Something went wrong',
  'workout.library.errorMessage': 'Your exercise library could not be loaded right now. Try again.',
  'workout.library.addAccessibility': 'Add a custom exercise',
  'workout.library.addTitle': 'Add a custom exercise',
  'workout.library.yourExercises': 'Your custom exercises',
  'workout.library.loading': 'Loading…',
  'workout.library.loadingAccessibility': 'Loading exercises',
  'workout.library.empty':
    'No custom exercises yet. Add one above to use it in your routines and workouts.',
  'workout.library.customAccessibility': 'Custom exercise',
  'workout.library.editTitle': 'Edit exercise',
  'workout.library.editAccessibility': 'Edit',
  'workout.library.edit': 'Edit',
  'workout.library.deleteAccessibility': 'Delete',
  'workout.library.delete': 'Delete',
  'workout.library.checkingUsage': 'Checking where this exercise is used…',
  'workout.library.usedIn': 'Used in',
  'workout.library.routineOne': 'routine',
  'workout.library.routineMany': 'routines',
  'workout.library.referencePreserved':
    'existing routines keep it; you just can’t add it to new ones.',
  'workout.library.notUsed':
    'This exercise isn’t used in any routines. Existing workout history is kept.',
  'workout.library.confirmDeleteAccessibility': 'Confirm delete',
  'workout.library.confirmDelete': 'Confirm delete',
  'workout.library.cancelDeleteAccessibility': 'Cancel delete',
  'workout.library.syncConflict': 'Sync conflict',
  'workout.library.syncPendingAccessibility': 'Sync pending',
  'workout.library.syncPending': 'Pending sync',
  'workout.library.builtInTitle': 'Built-in exercises',
  'workout.library.builtInDescription':
    'Provided by AppFitness. These read-only exercises use stable catalog identities and localized display names.',
  'workout.library.builtInAccessibility': 'Built-in exercise',
  'workout.muscle.back': 'Back',
  'workout.muscle.chest': 'Chest',
  'workout.muscle.core': 'Core',
  'workout.muscle.fullBody': 'Full body',
  'workout.muscle.glutes': 'Glutes',
  'workout.muscle.hamstrings': 'Hamstrings',
  'workout.muscle.quadriceps': 'Quadriceps',
  'workout.muscle.shoulders': 'Shoulders',
  'workout.muscle.triceps': 'Triceps',
  'workout.log.routeTitle': 'Log a workout',
  'workout.log.title': 'Log a workout',
  'workout.log.subtitle':
    'Track your sets as you train. Everything is saved on your device first and syncs to your account later.',
  'workout.log.errorTitle': 'Something went wrong',
  'workout.log.errorMessage': 'Your workouts could not be loaded right now. Try again.',
  'workout.log.defaultName': 'Workout',
  'workout.log.startAccessibility': 'Start a workout',
  'workout.log.startTitle': 'Start a workout',
  'workout.log.name': 'Workout name',
  'workout.log.namePlaceholder': 'e.g. Morning session',
  'workout.log.startButton': 'Start workout',
  'workout.log.fromRoutine': 'Or start from a routine',
  'workout.log.startFromAccessibility': 'Start workout from',
  'workout.log.openTitle': 'Open workouts',
  'workout.log.loading': 'Loading…',
  'workout.log.loadingAccessibility': 'Loading workouts',
  'workout.log.openEmpty': 'No open workouts.',
  'workout.log.workoutAccessibility': 'Workout:',
  'workout.log.savedAccessibility': 'Workout saved on this device',
  'workout.log.savedOnDevice': 'Saved on this device',
  'workout.log.logSetsAccessibility': 'Log sets for',
  'workout.log.logSets': 'Log sets',
  'workout.log.hideSets': 'Hide sets',
  'workout.log.finishAccessibility': 'Finish workout',
  'workout.log.finish': 'Finish',
  'workout.log.removeWorkoutAccessibility': 'Remove workout',
  'workout.log.remove': 'Remove',
  'workout.log.addSetTitle': 'Add a set',
  'workout.log.newCustomAccessibility': 'New custom exercise',
  'workout.log.createCustomAccessibility': 'Create a new custom exercise',
  'workout.log.newExercise': '+ New exercise',
  'workout.log.builtIn': 'Built-in',
  'workout.log.chooseAccessibility': 'Choose',
  'workout.log.myExercises': 'My exercises',
  'workout.log.customEmpty': 'No custom exercises yet.',
  'workout.log.reps': 'Reps',
  'workout.log.weightKg': 'Weight (kg)',
  'workout.log.addSet': 'Add set',
  'workout.log.recentTitle': 'Recent workouts',
  'workout.log.finishedWorkoutAccessibility': 'Finished workout:',
  'workout.log.finished': 'Finished',
  'workout.log.setsEmpty': 'No sets logged yet.',
  'workout.log.syncPendingAccessibility': 'Sync pending',
  'workout.log.syncPending': 'Pending sync',
  'workout.log.repsForSetAccessibility': 'Reps for set',
  'workout.log.markNotDoneAccessibility': 'Mark as not done, set',
  'workout.log.markDoneAccessibility': 'Mark as done, set',
  'workout.log.done': 'Done',
  'workout.log.markDone': 'Mark done',
  'workout.log.removeSetAccessibility': 'Remove set',
  'nutrition.routeTitle': 'Nutrition',
  'nutrition.plan.routeTitle': 'Meal plan',
  'nutrition.plan.title': '15-day meal plan',
  'nutrition.plan.subtitle':
    'A deterministic routine built from your iCoach targets and the local food catalog.',
  'nutrition.plan.logToday': "Log today's food",
  'nutrition.plan.logTodayAccessibility': 'Log the food you ate today',
  'nutrition.plan.loading': 'Loading…',
  'nutrition.plan.loadingAccessibility': 'Loading meal plan',
  'nutrition.plan.unavailable': 'Meal plan unavailable',
  'nutrition.plan.errorMessage': 'Your meal plan could not be built right now. Try again later.',
  'nutrition.plan.day': 'Day',
  'nutrition.plan.showDay': 'Show day',
  'nutrition.plan.breakfast': 'Breakfast',
  'nutrition.plan.lunch': 'Lunch',
  'nutrition.plan.dinner': 'Dinner',
  'nutrition.plan.snack': 'Snack',
  'nutrition.plan.meal': 'meal',
  'nutrition.plan.mealTotal': 'Meal total',
  'nutrition.plan.dayTotalsAccessibility': 'Day totals versus targets',
  'nutrition.plan.dayTotalTarget': 'Day total vs target',
  'nutrition.plan.calories': 'Calories',
  'nutrition.plan.protein': 'Protein',
  'nutrition.plan.carbs': 'Carbs',
  'nutrition.plan.fat': 'Fat',
  'nutrition.plan.targetSummary': 'target',
  'nutrition.plan.safeMinimumTitle': 'Safe minimum applied',
  'nutrition.plan.safeMinimumMessage':
    'The calorie target was raised to the safe minimum used by AppFitness.',
  'nutrition.plan.disclaimer':
    'These suggestions are general fitness guidance based on your profile and goal, not medical or dietary advice. Consult a qualified professional before making significant changes.',
  'nutrition.plan.preferencesAccessibility': 'Applied dietary preferences',
  'nutrition.plan.preferencesTitle': 'Your dietary preferences shaped this plan',
  'nutrition.plan.avoidedCategories': 'Avoided categories',
  'nutrition.plan.excludedFoods': 'Excluded foods',
  'nutrition.plan.preferencesExplanation':
    'Allergies and preferences deterministically remove foods before selection, so the plan reflects them. This is not medical advice.',
  'nutrition.targets.title': 'Nutrition targets',
  'nutrition.targets.subtitle':
    'Your daily calorie and macronutrient targets from your iCoach assessment.',
  'nutrition.targets.loadingAccessibility': 'Loading nutrition targets',
  'nutrition.targets.unavailable': 'Nutrition unavailable',
  'nutrition.targets.errorMessage': 'Your nutrition targets could not be loaded right now.',
  'nutrition.targets.calorieAccessibility': 'Daily calorie target',
  'nutrition.targets.dailyCalories': 'Daily calories',
  'nutrition.targets.macrosAccessibility': 'Macronutrient breakdown',
  'nutrition.targets.macros': 'Macros',
  'nutrition.targets.viewPlan': '15-day meal plan',
  'nutrition.targets.viewPlanAccessibility': 'View your 15-day meal plan',
  'nutrition.targets.maintenancePrefix': 'Calories are set at your maintenance level for',
  'nutrition.targets.adjustmentPrefix': 'Calories are set',
  'nutrition.targets.below': 'below',
  'nutrition.targets.above': 'above',
  'nutrition.targets.adjustmentSuffix': 'maintenance to support',
  'nutrition.goal.fatLoss': 'fat loss',
  'nutrition.goal.muscleGain': 'muscle gain',
  'nutrition.goal.recomposition': 'body recomposition',
  'nutrition.goal.strength': 'strength',
  'nutrition.goal.endurance': 'endurance',
  'nutrition.goal.generalHealth': 'general wellness',
  'nutrition.goal.rehabilitation': 'recovery',
  'nutrition.goal.maintenance': 'maintenance',
  'nutrition.preferences.routeTitle': 'Dietary preferences',
  'nutrition.preferences.title': 'Dietary preferences & allergies',
  'nutrition.preferences.subtitle':
    'Tell iCoach what to avoid. Allergies and preferences shape your meal suggestions and show advisory warnings without blocking your choices. Entries are saved on your device first and sync to your account later.',
  'nutrition.preferences.errorTitle': 'Something went wrong',
  'nutrition.preferences.errorMessage': 'Your dietary preferences could not be loaded right now.',
  'nutrition.preferences.addAccessibility': 'Add an exclusion',
  'nutrition.preferences.addTitle': 'Add an exclusion',
  'nutrition.preferences.what': 'What are you excluding?',
  'nutrition.preferences.categoryChoice': 'A category',
  'nutrition.preferences.foodChoice': 'A specific food',
  'nutrition.preferences.why': 'Why?',
  'nutrition.preferences.allergy': 'Allergy / sensitivity',
  'nutrition.preferences.preference': 'Preference / dislike',
  'nutrition.preferences.category': 'Category',
  'nutrition.preferences.findFood': 'Find a food',
  'nutrition.preferences.searchAccessibility': 'Search foods to exclude',
  'nutrition.preferences.searchPlaceholder': 'Search foods…',
  'nutrition.preferences.selected': 'Selected',
  'nutrition.preferences.noteAccessibility': 'Optional note',
  'nutrition.preferences.notePlaceholder': 'Optional note (encrypted on your device)',
  'nutrition.preferences.addButton': 'Add exclusion',
  'nutrition.preferences.listTitle': 'Your exclusions',
  'nutrition.preferences.loadingAccessibility': 'Loading dietary preferences',
  'nutrition.preferences.empty': 'No exclusions yet.',
  'nutrition.preferences.exclusion': 'Exclusion',
  'nutrition.preferences.categorySuffix': 'category',
  'nutrition.preferences.foodSuffix': 'food',
  'nutrition.preferences.noteSaved': 'note saved',
  'nutrition.preferences.remove': 'Remove',
  'nutrition.preferences.removeAccessibility': 'Remove exclusion',
  'nutrition.log.routeTitle': 'Food log',
  'nutrition.log.title': 'Food log',
  'nutrition.log.subtitle':
    'Log what you eat today. Saved on your device first, synced when online.',
  'nutrition.log.syncingTitle': 'Syncing',
  'nutrition.log.syncingMessage': 'Sending your food log.',
  'nutrition.log.offlineTitle': 'Offline',
  'nutrition.log.offlineMessage': 'Your log is saved on this device and will sync later.',
  'nutrition.log.actionTitle': 'Action needed',
  'nutrition.log.actionMessageOne':
    'item cannot sync because the food is not available on the server. Remove and re-add it to continue.',
  'nutrition.log.actionMessageMany':
    'items cannot sync because the food is not available on the server. Remove and re-add them to continue.',
  'nutrition.log.syncErrorTitle': 'Sync needs attention',
  'nutrition.log.syncErrorMessage': 'Your log is saved locally. We will try again.',
  'nutrition.log.pendingTitle': 'Changes pending',
  'nutrition.log.pendingMessageOne': 'change is waiting to sync.',
  'nutrition.log.pendingMessageMany': 'changes are waiting to sync.',
  'nutrition.log.syncedTitle': 'Log up to date',
  'nutrition.log.syncedMessage': 'Your food log is saved and synced.',
  'nutrition.log.actionAccessibility': 'Sync action required',
  'nutrition.log.pendingAccessibility': 'Sync pending',
  'nutrition.log.actionShort': 'Action needed',
  'nutrition.log.pendingShort': 'Pending sync',
  'nutrition.log.servings': 'servings',
  'nutrition.log.remove': 'Remove',
  'nutrition.log.removeAccessibility': 'Remove',
  'nutrition.log.entries': 'entries',
  'nutrition.log.totalsAccessibility': 'Daily totals from your logged entries',
  'nutrition.log.totals': "Today's totals",
  'nutrition.log.fiber': 'Fiber',
  'nutrition.log.loadingAccessibility': 'Loading food log',
  'nutrition.log.unavailable': 'Food log unavailable',
  'nutrition.log.errorMessage': 'Your food log could not be loaded right now. Please try again.',
  'nutrition.log.emptyAccessibility': 'No food logged yet',
  'nutrition.log.emptyTitle': 'Nothing logged yet',
  'nutrition.log.emptyMessage':
    'Search the catalog above and add your first food to see your daily totals.',
  'nutrition.log.syncNow': 'Sync now',
  'nutrition.log.syncNowAccessibility': 'Sync your food log now',
  'nutrition.log.addAccessibility': 'Add a food to your log',
  'nutrition.log.addTitle': 'Add food',
  'nutrition.log.mealAccessibility': 'Meal',
  'nutrition.log.searchAccessibility': 'Search foods',
  'nutrition.log.searchPlaceholder': 'Search foods (e.g. chicken, oats)',
  'nutrition.log.choose': 'Choose',
  'nutrition.log.noResults': 'No foods match that search.',
  'nutrition.log.oneServing': '1 serving',
  'nutrition.log.addButton': 'Add to log',
  'nutrition.log.logAccessibility': 'Log',
  'nutrition.log.decreaseServings': 'Decrease servings',
  'nutrition.log.increaseServings': 'Increase servings',
  'nutrition.warning.allergyTitle': 'Heads up — this matches an allergy or sensitivity',
  'nutrition.warning.preferenceTitle': 'This is on your avoid list',
  'nutrition.warning.catalogReason': 'a food you chose to avoid',
  'nutrition.warning.matches': 'matches',
  'nutrition.warning.join': 'and',
  'nutrition.warning.allergyAdvice':
    'You can still log it, but double-check that it is safe for you. This is not emergency medical advice.',
  'nutrition.warning.preferenceAdvice':
    'in your dietary preferences. You can still log it if you would like.',
  'nutrition.avoid.nuts': 'Nuts',
  'nutrition.avoid.shellfish': 'Shellfish',
  'nutrition.avoid.gluten': 'Gluten',
  'nutrition.avoid.lactose': 'Lactose / dairy',
  'nutrition.avoid.sodium': 'High sodium',
  'nutrition.avoid.purine': 'High purine',
  'nutrition.unit.g': 'g',
  'nutrition.unit.ml': 'ml',
  'nutrition.unit.piece': 'piece',
  'nutrition.unit.cup': 'cup',
  'nutrition.unit.tbsp': 'tbsp',
  'nutrition.unit.tsp': 'tsp',
  'nutrition.unit.slice': 'slice',
  'nutrition.gap.planAccessibility': 'Meal plan needs more data',
  'nutrition.gap.targetsAccessibility': 'Nutrition needs more data',
  'nutrition.gap.title': 'Finish your baseline first',
  'nutrition.gap.description':
    'Nutrition targets need your profile (birth date and height) and a recent weight.',
  'nutrition.gap.planSuffix': 'Your 15-day meal plan builds on those targets.',
  'nutrition.gap.profileTitle': 'Add your profile details',
  'nutrition.gap.profileButton': 'Create or edit profile',
  'nutrition.gap.profileAccessibility': 'Create or edit your profile',
  'nutrition.gap.weightTitle': 'Record a weight',
  'nutrition.gap.weightButton': 'Record weight',
  'nutrition.gap.weightAccessibility': 'Record your body weight',
  'nutrition.gap.dashboardButton': 'Go to dashboard',
  'nutrition.gap.dashboardAccessibility': 'Go to the dashboard to finish your baseline',
  'nutrition.gap.profileDetail': 'A profile is required.',
  'nutrition.gap.birthDateDetail': 'Your birth date is required.',
  'nutrition.gap.heightDetail': 'Your height is required.',
  'nutrition.gap.weightDetail': 'A recent weight is required.',
  'nutrition.gap.wellnessNotice':
    'AppFitness uses self-entered wellness data for these suggestions. It does not request diagnoses, prescriptions, doctor notes, or professional medical restrictions.',
  'dashboard.routeTitle': 'Dashboard',
  'dashboard.subtitle': 'Your local iCoach assessment',
  'dashboard.unavailable': 'Dashboard unavailable',
  'dashboard.errorMessage': 'Your dashboard could not be loaded right now. Please try again.',
  'dashboard.syncAccessibility': 'Synchronize local changes',
  'dashboard.syncNow': 'Sync now',
  'dashboard.recommendations': 'iCoach recommendations',
  'dashboard.nutritionAccessibility': 'View nutrition targets',
  'dashboard.nutrition': 'Nutrition',
  'dashboard.preferencesAccessibility': 'Manage dietary preferences and allergies',
  'dashboard.preferences': 'Dietary preferences',
  'dashboard.routinesAccessibility': 'Manage workout routines',
  'dashboard.routines': 'Workout routines',
  'dashboard.workoutLogAccessibility': 'Log a workout',
  'dashboard.workoutLog': 'Log a workout',
  'dashboard.exercisesAccessibility': 'Manage your exercise library',
  'dashboard.exercises': 'Exercise library',
  'dashboard.progressAccessibility': 'Track your progress',
  'dashboard.progress': 'Progress',
  'dashboard.signOutAccessibility': 'Sign out of your account',
  'dashboard.signOut': 'Sign out',
  'dashboard.deleteAccountAccessibility': 'Delete your account',
  'dashboard.deleteAccount': 'Delete account',
  'account.delete.screenTitle': 'Delete account',
  'account.delete.title': 'Delete account',
  'account.delete.description':
    'This permanently deletes your account and all your data. This cannot be undone.',
  'account.delete.errorTitle': 'Deletion failed',
  'account.delete.errorMessage': 'We could not delete your account. Please try again.',
  'account.delete.confirmInstruction': 'Type {phrase} to confirm',
  'account.delete.confirmationAccessibility': 'Deletion confirmation phrase',
  'account.delete.deleteAccessibility': 'Permanently delete account',
  'account.delete.deleteButton': 'Delete my account',
  'account.delete.cancelAccessibility': 'Cancel account deletion',
  'account.delete.cancel': 'Cancel',
  'dashboard.gap.accessibility': 'Dashboard setup requirements',
  'dashboard.gap.title': 'Finish your baseline',
  'dashboard.gap.description':
    'The dashboard runs entirely from local data. Add the basics below to unlock your first iCoach assessment.',
  'dashboard.gap.fixAccessibility': 'Fix',
  'dashboard.gap.addNow': 'Add now',
  'dashboard.gap.sampleAccessibility': 'Load fake sample dashboard data',
  'dashboard.gap.sampleButton': 'Load sample data',
  'dashboard.gap.profileTitle': 'Create your profile',
  'dashboard.gap.profileDetail': 'The dashboard needs your profile to calculate safe targets.',
  'dashboard.gap.birthDateTitle': 'Add your birth date',
  'dashboard.gap.birthDateDetail': 'Age is required for BMR and safety checks.',
  'dashboard.gap.heightTitle': 'Add your height',
  'dashboard.gap.heightDetail': 'Height is required for BMI and calorie calculations.',
  'dashboard.gap.weightTitle': 'Record a weight measurement',
  'dashboard.gap.weightDetail': 'Weight is required for body composition and nutrition targets.',
  'dashboard.gap.goalTitle': 'Using maintenance goal',
  'dashboard.gap.goalDetail': 'Set a goal to personalize calorie and training adjustments.',
  'dashboard.gap.sexTitle': 'Using undisclosed sex coefficients',
  'dashboard.gap.sexDetail': 'Add sex in your profile to improve BMR precision.',
  'dashboard.sync.syncingTitle': 'Syncing',
  'dashboard.sync.syncingMessage': 'Sending local changes.',
  'dashboard.sync.offlineTitle': 'Offline',
  'dashboard.sync.offlineMessage': 'Showing local data.',
  'dashboard.sync.errorTitle': 'Sync needs attention',
  'dashboard.sync.errorMessage': 'Your local changes are safe. We will try again.',
  'dashboard.sync.conflictsTitle': 'Conflicts pending',
  'dashboard.sync.conflictOne': 'item needs review.',
  'dashboard.sync.conflictMany': 'items need review.',
  'dashboard.sync.pendingTitle': 'Local changes pending',
  'dashboard.sync.pendingOne': 'pending',
  'dashboard.sync.pendingMany': 'pending',
  'dashboard.sync.failedOne': 'failed retry.',
  'dashboard.sync.failedMany': 'failed retries.',
  'dashboard.sync.readyTitle': 'Local data ready',
  'dashboard.sync.readyMessage': 'Dashboard is available offline.',
  'dashboard.assessment.accessibility': "Today's assessment summary",
  'dashboard.assessment.title': "Today's assessment",
  'dashboard.assessment.bmi': 'BMI',
  'dashboard.assessment.protein': 'Protein',
  'dashboard.assessment.carbs': 'Carbs',
  'dashboard.assessment.fat': 'Fat',
  'dashboard.assessment.training': 'Training',
  'dashboard.training.blocked': 'Blocked',
  'dashboard.bmi.underweight': 'underweight',
  'dashboard.bmi.normal': 'normal',
  'dashboard.bmi.overweight': 'overweight',
  'dashboard.bmi.obese': 'obese',
  'dashboard.intensity.low': 'low',
  'dashboard.intensity.moderate': 'moderate',
  'dashboard.intensity.high': 'high',
  'dashboard.recommendation.accessibility': 'recommendation',
  'dashboard.recommendation.evidence': 'Evidence',
  'dashboard.recommendation.category.safety': 'Safety',
  'dashboard.recommendation.category.nutrition': 'Nutrition',
  'dashboard.recommendation.category.training': 'Training',
  'dashboard.recommendation.category.recovery': 'Recovery',
  'dashboard.recommendation.category.body': 'Body composition',
  'dashboard.recommendation.priority.low': 'Low',
  'dashboard.recommendation.priority.medium': 'Medium',
  'dashboard.recommendation.priority.high': 'High',
  'dashboard.recommendation.priority.critical': 'Critical',
  'dashboard.recommendation.calorieTitle': 'Daily calorie target',
  'dashboard.recommendation.calorieExplanation':
    'Your estimated daily expenditure is {tdee} kcal, with a {adjustment}% goal adjustment.',
  'dashboard.recommendation.calorieSafetyFloor':
    'Your goal implies a deficit, but iCoach raised the target to a conservative energy floor.',
  'dashboard.recommendation.calorieEvidence':
    'Deterministic basal-metabolism formula with a standard activity multiplier.',
  'dashboard.recommendation.macrosTitle':
    'Macros: {protein} g protein / {carbs} g carbs / {fat} g fat',
  'dashboard.recommendation.macrosExplanation':
    'Protein is based on body weight, fat supports essential functions, and carbohydrates complete the remaining energy target.',
  'dashboard.recommendation.macrosEvidence':
    'ISSN guidance on protein and macronutrient distribution.',
  'dashboard.recommendation.trainingTitle': 'Train {days}× per week at {intensity} intensity',
  'dashboard.recommendation.trainingExplanation':
    'The plan uses your fitness level and goal, with conservative adjustments when recovery requires them.',
  'dashboard.recommendation.trainingEvidence':
    'Progressive overload with RPE-based autoregulation.',
  'dashboard.recommendation.sleepTitle': 'Prioritize sleep',
  'dashboard.recommendation.sleepExplanation':
    'An average of {hours} hours of sleep can limit recovery and performance, so training intensity was adjusted.',
  'dashboard.recommendation.sleepEvidence':
    'Sleep duration influences recovery, energy regulation, and training adaptation.',
  'dashboard.recommendation.underweightTitle': 'Fat loss is not recommended at your current BMI',
  'dashboard.recommendation.underweightExplanation':
    'Your BMI ({bmi}) is in the underweight range. A calorie deficit could be unsafe; choose a maintenance or gain-oriented goal.',
  'dashboard.recommendation.underweightEvidence':
    'WHO BMI classification and conservative energy-balance guidance.',
} as const;

export type TranslationKey = keyof typeof en;
