import type { TranslationKey } from './en';

export const es = {
  'language.title': 'Idioma',
  'language.description': 'Elige el idioma que usa AppFitness.',
  'language.system': 'Idioma del dispositivo',
  'language.english': 'Inglés',
  'language.spanish': 'Español',
  'language.saveError': 'No se pudo guardar el idioma. Inténtalo de nuevo.',
  'auth.screenTitle': 'Iniciar sesión',
  'auth.subtitle': 'Inicia sesión para continuar.',
  'auth.email': 'Correo electrónico',
  'auth.username': 'Nombre de usuario',
  'auth.password': 'Contraseña',
  'auth.signIn': 'Iniciar sesión',
  'auth.register': 'Registrarse',
  'auth.useExistingAccount': 'Usar una cuenta existente',
  'auth.createAccount': 'Crear una cuenta local',
  'auth.switchMode': 'Cambiar modo de autenticación',
  'auth.errorTitle': 'Error de inicio de sesión',
  'auth.errorMessage': 'No se pudo autenticar. Revisa tus credenciales y conexión.',
  'progress.measurements.accessibility': 'Registrar medidas corporales',
  'progress.measurements.title': 'Registrar medidas',
  'progress.measurements.date': 'Fecha',
  'progress.measurements.waist': 'Cintura (cm, opcional)',
  'progress.measurements.waistPlaceholder': 'p. ej., 82',
  'progress.measurements.hip': 'Cadera (cm, opcional)',
  'progress.measurements.hipPlaceholder': 'p. ej., 96',
  'progress.measurements.chest': 'Pecho (cm, opcional)',
  'progress.measurements.chestPlaceholder': 'p. ej., 100',
  'progress.measurements.bodyFat': 'Grasa corporal (%, opcional)',
  'progress.measurements.bodyFatPlaceholder': 'p. ej., 18',
  'progress.measurements.muscleMass': 'Masa muscular (kg, opcional)',
  'progress.measurements.muscleMassPlaceholder': 'p. ej., 35',
  'progress.measurements.muscleMassRange':
    'Ingresa una masa muscular mayor que 0 y de hasta 300 kg',
  'progress.measurements.atLeastOne': 'Ingresa al menos una medida corporal',
  'progress.measurements.notes': 'Notas (opcional)',
  'progress.measurements.notesPlaceholder': 'Algo que quieras recordar',
  'progress.measurements.save': 'Guardar medidas',
  'progress.measurements.saveAccessibility': 'Guardar medidas corporales',
  'progress.trends.muscleMass': 'Masa muscular',
  'nutrition.plan.routeTitle': 'Plan alimentario',
  'nutrition.plan.title': 'Plan alimentario de 15 días',
  'nutrition.plan.subtitle':
    'Una rutina determinista creada con tus objetivos de iCoach y el catálogo local de alimentos.',
  'nutrition.plan.logToday': 'Registrar alimentos de hoy',
  'nutrition.plan.logTodayAccessibility': 'Registrar los alimentos que consumiste hoy',
  'nutrition.plan.loading': 'Cargando…',
  'nutrition.plan.loadingAccessibility': 'Cargando el plan alimentario',
  'nutrition.plan.unavailable': 'Plan alimentario no disponible',
  'nutrition.plan.errorMessage':
    'No se pudo crear tu plan alimentario en este momento. Inténtalo más tarde.',
  'nutrition.plan.day': 'Día',
  'nutrition.plan.showDay': 'Mostrar día',
  'nutrition.plan.breakfast': 'Desayuno',
  'nutrition.plan.lunch': 'Almuerzo',
  'nutrition.plan.dinner': 'Cena',
  'nutrition.plan.snack': 'Merienda',
  'nutrition.plan.meal': 'comida',
  'nutrition.plan.mealTotal': 'Total de la comida',
  'nutrition.plan.dayTotalsAccessibility': 'Totales diarios comparados con los objetivos',
  'nutrition.plan.dayTotalTarget': 'Total diario frente al objetivo',
  'nutrition.plan.calories': 'Calorías',
  'nutrition.plan.protein': 'Proteína',
  'nutrition.plan.carbs': 'Carbohidratos',
  'nutrition.plan.fat': 'Grasa',
  'nutrition.plan.targetSummary': 'objetivo',
  'nutrition.plan.safeMinimumTitle': 'Mínimo seguro aplicado',
  'nutrition.plan.safeMinimumMessage':
    'El objetivo de calorías se elevó al mínimo seguro utilizado por AppFitness.',
  'nutrition.plan.disclaimer':
    'Estas sugerencias son una guía general de bienestar físico basada en tu perfil y objetivo; no constituyen asesoramiento médico ni dietético. Consulta a un profesional calificado antes de realizar cambios importantes.',
  'nutrition.plan.preferencesAccessibility': 'Preferencias alimentarias aplicadas',
  'nutrition.plan.preferencesTitle': 'Tus preferencias alimentarias definieron este plan',
  'nutrition.plan.avoidedCategories': 'Categorías evitadas',
  'nutrition.plan.excludedFoods': 'Alimentos excluidos',
  'nutrition.plan.preferencesExplanation':
    'Las alergias y preferencias eliminan alimentos de forma determinista antes de seleccionarlos, por lo que el plan las refleja. Esto no es asesoramiento médico.',
  'nutrition.avoid.nuts': 'Frutos secos',
  'nutrition.avoid.shellfish': 'Mariscos',
  'nutrition.avoid.gluten': 'Gluten',
  'nutrition.avoid.lactose': 'Lactosa / lácteos',
  'nutrition.avoid.sodium': 'Alto contenido de sodio',
  'nutrition.avoid.purine': 'Alto contenido de purinas',
  'nutrition.unit.g': 'g',
  'nutrition.unit.ml': 'ml',
  'nutrition.unit.piece': 'unidad',
  'nutrition.unit.cup': 'taza',
  'nutrition.unit.tbsp': 'cda.',
  'nutrition.unit.tsp': 'cdta.',
  'nutrition.unit.slice': 'rebanada',
  'nutrition.gap.planAccessibility': 'El plan alimentario necesita más datos',
  'nutrition.gap.targetsAccessibility': 'La nutrición necesita más datos',
  'nutrition.gap.title': 'Completa primero tus datos básicos',
  'nutrition.gap.description':
    'Los objetivos de nutrición necesitan tu perfil (fecha de nacimiento y estatura) y un peso reciente.',
  'nutrition.gap.planSuffix': 'Tu plan alimentario de 15 días se basa en esos objetivos.',
  'nutrition.gap.profileTitle': 'Agrega los datos de tu perfil',
  'nutrition.gap.profileButton': 'Crear o editar perfil',
  'nutrition.gap.profileAccessibility': 'Crear o editar tu perfil',
  'nutrition.gap.weightTitle': 'Registra un peso',
  'nutrition.gap.weightButton': 'Registrar peso',
  'nutrition.gap.weightAccessibility': 'Registrar tu peso corporal',
  'nutrition.gap.dashboardButton': 'Ir al panel',
  'nutrition.gap.dashboardAccessibility': 'Ir al panel para completar tus datos básicos',
  'nutrition.gap.profileDetail': 'Se requiere un perfil.',
  'nutrition.gap.birthDateDetail': 'Se requiere tu fecha de nacimiento.',
  'nutrition.gap.heightDetail': 'Se requiere tu estatura.',
  'nutrition.gap.weightDetail': 'Se requiere un peso reciente.',
  'nutrition.gap.wellnessNotice':
    'AppFitness usa datos de bienestar ingresados por ti para estas sugerencias. No solicita diagnósticos, recetas, notas médicas ni restricciones médicas profesionales.',
} as const satisfies Record<TranslationKey, string>;
