import type { TranslationKey } from './en';

export const es = {
  'language.title': 'Idioma',
  'language.description': 'Elige el idioma que usa AppFitness.',
  'language.system': 'Idioma del dispositivo',
  'language.english': 'Inglés',
  'language.spanish': 'Español',
  'language.saveError': 'No se pudo guardar el idioma. Inténtalo de nuevo.',
  'auth.screenTitle': 'Iniciar sesión',
  'auth.subtitle': 'Inicia sesión para continuar.',
  'auth.email': 'Correo electrónico',
  'auth.username': 'Nombre de usuario',
  'auth.password': 'Contraseña',
  'auth.signIn': 'Iniciar sesión',
  'auth.register': 'Registrarse',
  'auth.useExistingAccount': 'Usar una cuenta existente',
  'auth.createAccount': 'Crear una cuenta local',
  'auth.switchMode': 'Cambiar modo de autenticación',
  'auth.errorTitle': 'Error de inicio de sesión',
  'auth.errorMessage': 'No se pudo autenticar. Revisa tus credenciales y conexión.',
  'progress.measurements.accessibility': 'Registrar medidas corporales',
  'progress.measurements.title': 'Registrar medidas',
  'progress.measurements.date': 'Fecha',
  'progress.measurements.waist': 'Cintura (cm, opcional)',
  'progress.measurements.waistPlaceholder': 'p. ej., 82',
  'progress.measurements.hip': 'Cadera (cm, opcional)',
  'progress.measurements.hipPlaceholder': 'p. ej., 96',
  'progress.measurements.chest': 'Pecho (cm, opcional)',
  'progress.measurements.chestPlaceholder': 'p. ej., 100',
  'progress.measurements.bodyFat': 'Grasa corporal (%, opcional)',
  'progress.measurements.bodyFatPlaceholder': 'p. ej., 18',
  'progress.measurements.muscleMass': 'Masa muscular (kg, opcional)',
  'progress.measurements.muscleMassPlaceholder': 'p. ej., 35',
  'progress.measurements.muscleMassRange':
    'Ingresa una masa muscular mayor que 0 y de hasta 300 kg',
  'progress.measurements.atLeastOne': 'Ingresa al menos una medida corporal',
  'progress.measurements.notes': 'Notas (opcional)',
  'progress.measurements.notesPlaceholder': 'Algo que quieras recordar',
  'progress.measurements.save': 'Guardar medidas',
  'progress.measurements.saveAccessibility': 'Guardar medidas corporales',
  'progress.trends.muscleMass': 'Masa muscular',
} as const satisfies Record<TranslationKey, string>;
