import type { TranslationKey } from './en';

export const es = {
  'language.title': 'Idioma',
  'language.description': 'Elige el idioma que usa AppFitness.',
  'language.system': 'Idioma del dispositivo',
  'language.english': 'Inglés',
  'language.spanish': 'Español',
  'language.saveError': 'No se pudo guardar el idioma. Inténtalo de nuevo.',
  'auth.screenTitle': 'Iniciar sesión',
  'auth.subtitle': 'Inicia sesión para continuar.',
  'auth.email': 'Correo electrónico',
  'auth.username': 'Nombre de usuario',
  'auth.password': 'Contraseña',
  'auth.signIn': 'Iniciar sesión',
  'auth.register': 'Registrarse',
  'auth.useExistingAccount': 'Usar una cuenta existente',
  'auth.createAccount': 'Crear una cuenta local',
  'auth.switchMode': 'Cambiar modo de autenticación',
  'auth.errorTitle': 'Error de inicio de sesión',
  'auth.errorMessage': 'No se pudo autenticar. Revisa tus credenciales y conexión.',
  'progress.measurements.accessibility': 'Registrar medidas corporales',
  'progress.measurements.title': 'Registrar medidas',
  'progress.measurements.date': 'Fecha',
  'progress.measurements.waist': 'Cintura (cm, opcional)',
  'progress.measurements.waistPlaceholder': 'p. ej., 82',
  'progress.measurements.hip': 'Cadera (cm, opcional)',
  'progress.measurements.hipPlaceholder': 'p. ej., 96',
  'progress.measurements.chest': 'Pecho (cm, opcional)',
  'progress.measurements.chestPlaceholder': 'p. ej., 100',
  'progress.measurements.bodyFat': 'Grasa corporal (%, opcional)',
  'progress.measurements.bodyFatPlaceholder': 'p. ej., 18',
  'progress.measurements.muscleMass': 'Masa muscular (kg, opcional)',
  'progress.measurements.muscleMassPlaceholder': 'p. ej., 35',
  'progress.measurements.muscleMassRange':
    'Ingresa una masa muscular mayor que 0 y de hasta 300 kg',
  'progress.measurements.atLeastOne': 'Ingresa al menos una medida corporal',
  'progress.measurements.notes': 'Notas (opcional)',
  'progress.measurements.notesPlaceholder': 'Algo que quieras recordar',
  'progress.measurements.save': 'Guardar medidas',
  'progress.measurements.saveAccessibility': 'Guardar medidas corporales',
  'progress.trends.muscleMass': 'Masa muscular',
  'workout.plan.accessibility': 'Tu plan determinista de ejercicios de iCoach',
  'workout.plan.routeTitle': 'Rutinas de ejercicios',
  'workout.plan.title': 'Tu plan semanal de iCoach',
  'workout.plan.subtitle':
    'Creado de forma determinista según tu objetivo, nivel físico, horario y equipo disponible.',
  'workout.plan.loading': 'Creando tu plan de ejercicios…',
  'workout.plan.gapTitle': 'Completa primero tus datos básicos',
  'workout.plan.gapMessage':
    'Tu plan de ejercicios necesita un perfil y una evaluación física completos.',
  'workout.plan.blockedTitle': 'Plan de ejercicios no disponible',
  'workout.plan.blockedMessage':
    'Tu evaluación actual no permite crear un plan. Revisa tus datos de bienestar antes de continuar.',
  'workout.plan.errorTitle': 'El plan de ejercicios necesita atención',
  'workout.plan.errorMessage':
    'No se pudo crear una rutina completa con el equipo y las limitaciones actuales.',
  'workout.plan.unsupportedTitle': 'Equipo no reconocido',
  'workout.plan.unsupportedMessage':
    'Estos valores del perfil no se utilizaron. Cámbialos por una opción de equipo compatible:',
  'workout.plan.schedule': 'Horario semanal',
  'workout.plan.sessions': 'Sesiones de entrenamiento',
  'workout.plan.progression': 'Cómo progresar',
  'workout.plan.training': 'Entrenamiento',
  'workout.plan.activeRecovery': 'Recuperación activa',
  'workout.plan.fullRest': 'Descanso completo',
  'workout.plan.session': 'Sesión',
  'workout.plan.fullBody': 'Cuerpo completo',
  'workout.plan.sets': 'series',
  'workout.plan.reps': 'repeticiones',
  'workout.plan.seconds': 'segundos',
  'workout.plan.rest': 'descanso',
  'workout.plan.targetRpe': 'RPE objetivo',
  'workout.plan.substitutions': 'Sustituciones',
  'workout.plan.afterSessions': 'Después de sesiones exitosas',
  'workout.plan.addLoad': 'aumenta la carga en',
  'workout.plan.addRepetitions': 'agrega repeticiones',
  'workout.plan.addDuration': 'agrega segundos',
  'workout.plan.wellnessNotice':
    'Solo orientación general de bienestar físico. Detente si un ejercicio causa dolor y adapta el plan a tus limitaciones físicas declaradas.',
  'workout.day.monday': 'Lunes',
  'workout.day.tuesday': 'Martes',
  'workout.day.wednesday': 'Miércoles',
  'workout.day.thursday': 'Jueves',
  'workout.day.friday': 'Viernes',
  'workout.day.saturday': 'Sábado',
  'workout.day.sunday': 'Domingo',
  'workout.builder.title': 'Rutinas de ejercicios',
  'workout.builder.subtitle':
    'Crea rutinas reutilizables con ejercicios integrados y personalizados. Se guardan primero en tu dispositivo y luego se sincronizan con tu cuenta.',
  'workout.builder.errorTitle': 'Algo salió mal',
  'workout.builder.errorMessage':
    'No se pudieron cargar tus rutinas en este momento. Inténtalo de nuevo.',
  'workout.builder.createAccessibility': 'Crear una rutina',
  'workout.builder.createTitle': 'Crear una rutina',
  'workout.builder.name': 'Nombre de la rutina',
  'workout.builder.namePlaceholder': 'p. ej., Día de empuje',
  'workout.builder.createButton': 'Crear rutina',
  'workout.builder.yourRoutines': 'Tus rutinas',
  'workout.builder.loading': 'Cargando…',
  'workout.builder.loadingAccessibility': 'Cargando rutinas',
  'workout.builder.empty': 'Todavía no hay rutinas.',
  'workout.builder.routineAccessibility': 'Rutina:',
  'workout.builder.viewExercises': 'Ver ejercicios',
  'workout.builder.hideExercises': 'Ocultar ejercicios',
  'workout.builder.viewExercisesAccessibility': 'Ver los ejercicios de',
  'workout.builder.removeRoutineAccessibility': 'Eliminar la rutina',
  'workout.builder.remove': 'Eliminar',
  'workout.builder.addExercise': 'Agregar un ejercicio',
  'workout.builder.newCustomAccessibility': 'Nuevo ejercicio personalizado',
  'workout.builder.createCustomAccessibility': 'Crear un ejercicio personalizado',
  'workout.builder.newExercise': '+ Nuevo ejercicio',
  'workout.builder.builtIn': 'Integrados',
  'workout.builder.myExercises': 'Mis ejercicios',
  'workout.builder.customEmpty': 'Todavía no hay ejercicios personalizados.',
  'workout.builder.addAccessibility': 'Agregar',
  'workout.builder.routineExerciseEmpty': 'Esta rutina todavía no tiene ejercicios.',
  'workout.builder.removedExercise': '(ejercicio eliminado)',
  'workout.builder.removeFromRoutineAccessibility': 'Eliminar de la rutina:',
  'workout.custom.name': 'Nombre',
  'workout.custom.namePlaceholder': 'p. ej., sentadilla Zercher',
  'workout.custom.normalizedAccessibility': 'El nombre se guardará como',
  'workout.custom.normalizedPrefix': 'Se guardará como',
  'workout.custom.muscleGroup': 'Grupo muscular',
  'workout.custom.muscleGroupPlaceholder': 'p. ej., piernas',
  'workout.custom.category': 'Categoría',
  'workout.custom.categoryStrength': 'Fuerza',
  'workout.custom.categoryCardio': 'Cardio',
  'workout.custom.categoryFlexibility': 'Flexibilidad',
  'workout.custom.categoryBodyweight': 'Peso corporal',
  'workout.custom.instructions': 'Instrucciones (opcional)',
  'workout.custom.instructionsPlaceholder': 'Cómo realizarlo',
  'workout.custom.required': 'Obligatorio',
  'workout.custom.duplicateName': 'Ya tienes un ejercicio personalizado con ese nombre.',
  'workout.custom.saveChanges': 'Guardar cambios',
  'workout.custom.addExerciseAccessibility': 'Agregar ejercicio personalizado',
  'workout.custom.addExercise': 'Agregar ejercicio',
  'workout.custom.cancel': 'Cancelar',
  'workout.custom.noteAccessibility': 'Nota de bienestar para ejercicio personalizado',
  'workout.custom.note':
    'Los ejercicios personalizados no se comparan automáticamente con tus limitaciones físicas declaradas. Revisa cada ejercicio y detente si causa dolor.',
  'workout.exclusion.accessibility': 'Advertencia sobre limitaciones para el ejercicio',
  'workout.exclusion.warning': 'Puede entrar en conflicto con tus limitaciones físicas actuales',
  'workout.movement.deepSquat': 'sentadilla profunda',
  'workout.movement.lunge': 'zancada',
  'workout.movement.jumping': 'saltos',
  'workout.movement.running': 'carrera',
  'workout.movement.sprinting': 'carrera de velocidad',
  'workout.movement.highImpactCardio': 'cardio de alto impacto',
  'workout.movement.overheadPress': 'press sobre la cabeza',
  'workout.movement.behindNeckPress': 'press tras nuca',
  'workout.movement.dips': 'fondos',
  'workout.movement.heavyPressing': 'press con carga alta',
  'workout.movement.frontRackLoading': 'carga en posición frontal',
  'workout.movement.skullCrushers': 'extensión de tríceps acostado',
  'workout.movement.heavyHinge': 'bisagra de cadera con carga alta',
  'workout.movement.goodMorning': 'buenos días',
  'workout.movement.loadedSpinalFlexion': 'flexión de columna con carga',
  'workout.movement.loadedCarries': 'caminatas con carga',
  'workout.movement.bridging': 'puentes',
  'workout.movement.maxEffortLifts': 'levantamientos de esfuerzo máximo',
  'workout.movement.valsalvaHeavyLifts': 'levantamientos pesados conteniendo la respiración',
  'workout.library.title': 'Biblioteca de ejercicios',
  'workout.library.subtitle':
    'Crea tus propios ejercicios para usarlos en rutinas y entrenamientos. Se guardan primero en tu dispositivo y luego se sincronizan con tu cuenta.',
  'workout.library.errorTitle': 'Algo salió mal',
  'workout.library.errorMessage':
    'No se pudo cargar tu biblioteca de ejercicios en este momento. Inténtalo de nuevo.',
  'workout.library.addAccessibility': 'Agregar un ejercicio personalizado',
  'workout.library.addTitle': 'Agregar un ejercicio personalizado',
  'workout.library.yourExercises': 'Tus ejercicios personalizados',
  'workout.library.loading': 'Cargando…',
  'workout.library.loadingAccessibility': 'Cargando ejercicios',
  'workout.library.empty':
    'Todavía no tienes ejercicios personalizados. Agrega uno arriba para usarlo en tus rutinas y entrenamientos.',
  'workout.library.customAccessibility': 'Ejercicio personalizado',
  'workout.library.editTitle': 'Editar ejercicio',
  'workout.library.editAccessibility': 'Editar',
  'workout.library.edit': 'Editar',
  'workout.library.deleteAccessibility': 'Eliminar',
  'workout.library.delete': 'Eliminar',
  'workout.library.checkingUsage': 'Comprobando dónde se usa este ejercicio…',
  'workout.library.usedIn': 'Se usa en',
  'workout.library.routineOne': 'rutina',
  'workout.library.routineMany': 'rutinas',
  'workout.library.referencePreserved':
    'las rutinas existentes lo conservan; simplemente no podrás agregarlo a otras nuevas.',
  'workout.library.notUsed':
    'Este ejercicio no se usa en ninguna rutina. El historial de entrenamientos existente se conserva.',
  'workout.library.confirmDeleteAccessibility': 'Confirmar eliminación de',
  'workout.library.confirmDelete': 'Confirmar eliminación',
  'workout.library.cancelDeleteAccessibility': 'Cancelar eliminación',
  'workout.library.syncConflict': 'Conflicto de sincronización',
  'workout.library.syncPendingAccessibility': 'Sincronización pendiente',
  'workout.library.syncPending': 'Pendiente de sincronización',
  'workout.library.builtInTitle': 'Ejercicios integrados',
  'workout.library.builtInDescription':
    'Proporcionados por AppFitness. Estos ejercicios de solo lectura usan identidades estables del catálogo y nombres localizados.',
  'workout.library.builtInAccessibility': 'Ejercicio integrado',
  'workout.muscle.back': 'Espalda',
  'workout.muscle.chest': 'Pecho',
  'workout.muscle.core': 'Zona media',
  'workout.muscle.fullBody': 'Cuerpo completo',
  'workout.muscle.glutes': 'Glúteos',
  'workout.muscle.hamstrings': 'Isquiotibiales',
  'workout.muscle.quadriceps': 'Cuádriceps',
  'workout.muscle.shoulders': 'Hombros',
  'workout.muscle.triceps': 'Tríceps',
  'nutrition.plan.routeTitle': 'Plan alimentario',
  'nutrition.plan.title': 'Plan alimentario de 15 días',
  'nutrition.plan.subtitle':
    'Una rutina determinista creada con tus objetivos de iCoach y el catálogo local de alimentos.',
  'nutrition.plan.logToday': 'Registrar alimentos de hoy',
  'nutrition.plan.logTodayAccessibility': 'Registrar los alimentos que consumiste hoy',
  'nutrition.plan.loading': 'Cargando…',
  'nutrition.plan.loadingAccessibility': 'Cargando el plan alimentario',
  'nutrition.plan.unavailable': 'Plan alimentario no disponible',
  'nutrition.plan.errorMessage':
    'No se pudo crear tu plan alimentario en este momento. Inténtalo más tarde.',
  'nutrition.plan.day': 'Día',
  'nutrition.plan.showDay': 'Mostrar día',
  'nutrition.plan.breakfast': 'Desayuno',
  'nutrition.plan.lunch': 'Almuerzo',
  'nutrition.plan.dinner': 'Cena',
  'nutrition.plan.snack': 'Merienda',
  'nutrition.plan.meal': 'comida',
  'nutrition.plan.mealTotal': 'Total de la comida',
  'nutrition.plan.dayTotalsAccessibility': 'Totales diarios comparados con los objetivos',
  'nutrition.plan.dayTotalTarget': 'Total diario frente al objetivo',
  'nutrition.plan.calories': 'Calorías',
  'nutrition.plan.protein': 'Proteína',
  'nutrition.plan.carbs': 'Carbohidratos',
  'nutrition.plan.fat': 'Grasa',
  'nutrition.plan.targetSummary': 'objetivo',
  'nutrition.plan.safeMinimumTitle': 'Mínimo seguro aplicado',
  'nutrition.plan.safeMinimumMessage':
    'El objetivo de calorías se elevó al mínimo seguro utilizado por AppFitness.',
  'nutrition.plan.disclaimer':
    'Estas sugerencias son una guía general de bienestar físico basada en tu perfil y objetivo; no constituyen asesoramiento médico ni dietético. Consulta a un profesional calificado antes de realizar cambios importantes.',
  'nutrition.plan.preferencesAccessibility': 'Preferencias alimentarias aplicadas',
  'nutrition.plan.preferencesTitle': 'Tus preferencias alimentarias definieron este plan',
  'nutrition.plan.avoidedCategories': 'Categorías evitadas',
  'nutrition.plan.excludedFoods': 'Alimentos excluidos',
  'nutrition.plan.preferencesExplanation':
    'Las alergias y preferencias eliminan alimentos de forma determinista antes de seleccionarlos, por lo que el plan las refleja. Esto no es asesoramiento médico.',
  'nutrition.targets.title': 'Objetivos nutricionales',
  'nutrition.targets.subtitle':
    'Tus objetivos diarios de calorías y macronutrientes según tu evaluación de iCoach.',
  'nutrition.targets.loadingAccessibility': 'Cargando objetivos nutricionales',
  'nutrition.targets.unavailable': 'Nutrición no disponible',
  'nutrition.targets.errorMessage': 'No se pudieron cargar tus objetivos nutricionales.',
  'nutrition.targets.calorieAccessibility': 'Objetivo diario de calorías',
  'nutrition.targets.dailyCalories': 'Calorías diarias',
  'nutrition.targets.macrosAccessibility': 'Distribución de macronutrientes',
  'nutrition.targets.macros': 'Macronutrientes',
  'nutrition.targets.viewPlan': 'Plan alimentario de 15 días',
  'nutrition.targets.viewPlanAccessibility': 'Ver tu plan alimentario de 15 días',
  'nutrition.targets.maintenancePrefix':
    'Las calorías se mantienen en tu nivel de mantenimiento para',
  'nutrition.targets.adjustmentPrefix': 'Las calorías se establecen',
  'nutrition.targets.below': 'por debajo del',
  'nutrition.targets.above': 'por encima del',
  'nutrition.targets.adjustmentSuffix': 'nivel de mantenimiento para apoyar',
  'nutrition.goal.fatLoss': 'la pérdida de grasa',
  'nutrition.goal.muscleGain': 'el aumento de masa muscular',
  'nutrition.goal.recomposition': 'la recomposición corporal',
  'nutrition.goal.strength': 'la fuerza',
  'nutrition.goal.endurance': 'la resistencia',
  'nutrition.goal.generalHealth': 'el bienestar general',
  'nutrition.goal.rehabilitation': 'la recuperación',
  'nutrition.goal.maintenance': 'el mantenimiento',
  'nutrition.preferences.title': 'Preferencias y alergias alimentarias',
  'nutrition.preferences.subtitle':
    'Indica a iCoach qué debe evitar. Las alergias y preferencias adaptan tus sugerencias de comidas y muestran advertencias informativas sin bloquear tus decisiones. Los datos se guardan primero en tu dispositivo y luego se sincronizan con tu cuenta.',
  'nutrition.preferences.errorTitle': 'Algo salió mal',
  'nutrition.preferences.errorMessage': 'No se pudieron cargar tus preferencias alimentarias.',
  'nutrition.preferences.addAccessibility': 'Agregar una exclusión',
  'nutrition.preferences.addTitle': 'Agregar una exclusión',
  'nutrition.preferences.what': '¿Qué deseas excluir?',
  'nutrition.preferences.categoryChoice': 'Una categoría',
  'nutrition.preferences.foodChoice': 'Un alimento específico',
  'nutrition.preferences.why': '¿Por qué?',
  'nutrition.preferences.allergy': 'Alergia / sensibilidad',
  'nutrition.preferences.preference': 'Preferencia / desagrado',
  'nutrition.preferences.category': 'Categoría',
  'nutrition.preferences.findFood': 'Buscar un alimento',
  'nutrition.preferences.searchAccessibility': 'Buscar alimentos para excluir',
  'nutrition.preferences.searchPlaceholder': 'Buscar alimentos…',
  'nutrition.preferences.selected': 'Seleccionado',
  'nutrition.preferences.noteAccessibility': 'Nota opcional',
  'nutrition.preferences.notePlaceholder': 'Nota opcional (cifrada en tu dispositivo)',
  'nutrition.preferences.addButton': 'Agregar exclusión',
  'nutrition.preferences.listTitle': 'Tus exclusiones',
  'nutrition.preferences.loadingAccessibility': 'Cargando preferencias alimentarias',
  'nutrition.preferences.empty': 'Todavía no hay exclusiones.',
  'nutrition.preferences.exclusion': 'Exclusión',
  'nutrition.preferences.categorySuffix': 'categoría',
  'nutrition.preferences.foodSuffix': 'alimento',
  'nutrition.preferences.noteSaved': 'nota guardada',
  'nutrition.preferences.remove': 'Eliminar',
  'nutrition.preferences.removeAccessibility': 'Eliminar exclusión',
  'nutrition.log.title': 'Registro de alimentos',
  'nutrition.log.subtitle':
    'Registra lo que consumes hoy. Se guarda primero en tu dispositivo y se sincroniza cuando haya conexión.',
  'nutrition.log.syncingTitle': 'Sincronizando',
  'nutrition.log.syncingMessage': 'Enviando tu registro de alimentos.',
  'nutrition.log.offlineTitle': 'Sin conexión',
  'nutrition.log.offlineMessage':
    'Tu registro está guardado en este dispositivo y se sincronizará más tarde.',
  'nutrition.log.actionTitle': 'Acción necesaria',
  'nutrition.log.actionMessageOne':
    'elemento no puede sincronizarse porque el alimento no está disponible en el servidor. Elimínalo y agrégalo nuevamente para continuar.',
  'nutrition.log.actionMessageMany':
    'elementos no pueden sincronizarse porque el alimento no está disponible en el servidor. Elimínalos y agrégalos nuevamente para continuar.',
  'nutrition.log.syncErrorTitle': 'La sincronización necesita atención',
  'nutrition.log.syncErrorMessage':
    'Tu registro está guardado localmente. Lo intentaremos de nuevo.',
  'nutrition.log.pendingTitle': 'Cambios pendientes',
  'nutrition.log.pendingMessageOne': 'cambio está en espera de sincronización.',
  'nutrition.log.pendingMessageMany': 'cambios están en espera de sincronización.',
  'nutrition.log.syncedTitle': 'Registro actualizado',
  'nutrition.log.syncedMessage': 'Tu registro de alimentos está guardado y sincronizado.',
  'nutrition.log.actionAccessibility': 'Se requiere una acción de sincronización',
  'nutrition.log.pendingAccessibility': 'Sincronización pendiente',
  'nutrition.log.actionShort': 'Acción necesaria',
  'nutrition.log.pendingShort': 'Sincronización pendiente',
  'nutrition.log.servings': 'porciones',
  'nutrition.log.remove': 'Eliminar',
  'nutrition.log.removeAccessibility': 'Eliminar',
  'nutrition.log.entries': 'registros',
  'nutrition.log.totalsAccessibility': 'Totales diarios de tus alimentos registrados',
  'nutrition.log.totals': 'Totales de hoy',
  'nutrition.log.fiber': 'Fibra',
  'nutrition.log.loadingAccessibility': 'Cargando registro de alimentos',
  'nutrition.log.unavailable': 'Registro de alimentos no disponible',
  'nutrition.log.errorMessage': 'No se pudo cargar tu registro de alimentos. Inténtalo de nuevo.',
  'nutrition.log.emptyAccessibility': 'Todavía no hay alimentos registrados',
  'nutrition.log.emptyTitle': 'Todavía no has registrado alimentos',
  'nutrition.log.emptyMessage':
    'Busca en el catálogo y agrega tu primer alimento para ver los totales diarios.',
  'nutrition.log.syncNow': 'Sincronizar ahora',
  'nutrition.log.syncNowAccessibility': 'Sincronizar ahora tu registro de alimentos',
  'nutrition.log.addAccessibility': 'Agregar un alimento a tu registro',
  'nutrition.log.addTitle': 'Agregar alimento',
  'nutrition.log.mealAccessibility': 'Comida',
  'nutrition.log.searchAccessibility': 'Buscar alimentos',
  'nutrition.log.searchPlaceholder': 'Buscar alimentos (p. ej., pollo, avena)',
  'nutrition.log.choose': 'Elegir',
  'nutrition.log.noResults': 'Ningún alimento coincide con esa búsqueda.',
  'nutrition.log.oneServing': '1 porción',
  'nutrition.log.addButton': 'Agregar al registro',
  'nutrition.log.logAccessibility': 'Registrar',
  'nutrition.log.decreaseServings': 'Disminuir porciones',
  'nutrition.log.increaseServings': 'Aumentar porciones',
  'nutrition.warning.allergyTitle': 'Atención: coincide con una alergia o sensibilidad',
  'nutrition.warning.preferenceTitle': 'Este alimento está en tu lista de exclusión',
  'nutrition.warning.catalogReason': 'un alimento que decidiste evitar',
  'nutrition.warning.matches': 'coincide con',
  'nutrition.warning.join': 'y',
  'nutrition.warning.allergyAdvice':
    'Aún puedes registrarlo, pero confirma que sea seguro para ti. Esto no es asesoramiento médico de emergencia.',
  'nutrition.warning.preferenceAdvice':
    'en tus preferencias alimentarias. Aún puedes registrarlo si así lo deseas.',
  'nutrition.avoid.nuts': 'Frutos secos',
  'nutrition.avoid.shellfish': 'Mariscos',
  'nutrition.avoid.gluten': 'Gluten',
  'nutrition.avoid.lactose': 'Lactosa / lácteos',
  'nutrition.avoid.sodium': 'Alto contenido de sodio',
  'nutrition.avoid.purine': 'Alto contenido de purinas',
  'nutrition.unit.g': 'g',
  'nutrition.unit.ml': 'ml',
  'nutrition.unit.piece': 'unidad',
  'nutrition.unit.cup': 'taza',
  'nutrition.unit.tbsp': 'cda.',
  'nutrition.unit.tsp': 'cdta.',
  'nutrition.unit.slice': 'rebanada',
  'nutrition.gap.planAccessibility': 'El plan alimentario necesita más datos',
  'nutrition.gap.targetsAccessibility': 'La nutrición necesita más datos',
  'nutrition.gap.title': 'Completa primero tus datos básicos',
  'nutrition.gap.description':
    'Los objetivos de nutrición necesitan tu perfil (fecha de nacimiento y estatura) y un peso reciente.',
  'nutrition.gap.planSuffix': 'Tu plan alimentario de 15 días se basa en esos objetivos.',
  'nutrition.gap.profileTitle': 'Agrega los datos de tu perfil',
  'nutrition.gap.profileButton': 'Crear o editar perfil',
  'nutrition.gap.profileAccessibility': 'Crear o editar tu perfil',
  'nutrition.gap.weightTitle': 'Registra un peso',
  'nutrition.gap.weightButton': 'Registrar peso',
  'nutrition.gap.weightAccessibility': 'Registrar tu peso corporal',
  'nutrition.gap.dashboardButton': 'Ir al panel',
  'nutrition.gap.dashboardAccessibility': 'Ir al panel para completar tus datos básicos',
  'nutrition.gap.profileDetail': 'Se requiere un perfil.',
  'nutrition.gap.birthDateDetail': 'Se requiere tu fecha de nacimiento.',
  'nutrition.gap.heightDetail': 'Se requiere tu estatura.',
  'nutrition.gap.weightDetail': 'Se requiere un peso reciente.',
  'nutrition.gap.wellnessNotice':
    'AppFitness usa datos de bienestar ingresados por ti para estas sugerencias. No solicita diagnósticos, recetas, notas médicas ni restricciones médicas profesionales.',
} as const satisfies Record<TranslationKey, string>;
