/**
 * Spanish presentation names for the bundled food catalog (Phase 21 Slice 4B).
 *
 * Keys are the immutable catalog identifiers. These labels are presentation
 * data only: they never enter catalog identity, snapshots, macros, plan seeds,
 * persistence, or sync payloads.
 */
export const SPANISH_FOOD_NAMES: Readonly<Record<string, string>> = {
  'food.chicken_breast': 'Pechuga de pollo, cocida',
  'food.chicken_thigh': 'Muslo de pollo sin piel, cocido',
  'food.turkey_breast': 'Pechuga de pavo, cocida',
  'food.ground_turkey_lean': 'Pavo molido magro, cocido',
  'food.beef_sirloin': 'Solomillo de res magro, cocido',
  'food.ground_beef_lean': 'Carne molida de res magra (93 %), cocida',
  'food.beef_tenderloin': 'Lomo de res, cocido',
  'food.beef_flank': 'Falda de res, cocida',
  'food.pork_tenderloin': 'Solomillo de cerdo, cocido',
  'food.pork_loin_chop': 'Chuleta de lomo de cerdo, cocida',
  'food.pork_shoulder_lean': 'Paleta de cerdo magra, cocida',
  'food.lamb_loin': 'Lomo de cordero magro, cocido',
  'food.venison': 'Carne de venado, cocida',
  'food.bison': 'Carne de bisonte, cocida',
  'food.egg_whole': 'Huevo entero',
  'food.egg_white': 'Clara de huevo',
  'food.egg_omelette_plain': 'Tortilla de huevo sencilla (2 huevos)',
  'food.salmon_atlantic': 'Salmón del Atlántico, cocido',
  'food.salmon_sockeye': 'Salmón rojo, cocido',
  'food.tuna_canned_water': 'Atún enlatado en agua',
  'food.tuna_yellowfin': 'Atún de aleta amarilla, cocido',
  'food.cod': 'Bacalao, cocido',
  'food.haddock': 'Eglefino, cocido',
  'food.pollock': 'Abadejo, cocido',
  'food.tilapia': 'Tilapia, cocida',
  'food.halibut': 'Fletán, cocido',
  'food.rainbow_trout': 'Trucha arcoíris, cocida',
  'food.mackerel': 'Caballa, cocida',
  'food.sardines_canned': 'Sardinas enlatadas en agua',
  'food.shrimp': 'Camarones, cocidos',
  'food.crab': 'Cangrejo, cocido',
  'food.scallops': 'Vieiras, cocidas',
  'food.mussels': 'Mejillones, cocidos',
  'food.octopus': 'Pulpo, cocido',
  'food.chicken_drumstick': 'Pierna de pollo sin piel, cocida',
  'food.chicken_deli': 'Pechuga de pollo en lonchas',
  'food.turkey_deli': 'Pechuga de pavo en lonchas',
  'food.canadian_bacon': 'Tocino canadiense',
  'food.roast_chicken': 'Pollo asado, solo carne',
  'food.ahi_tuna_seared': 'Filete de atún ahi, sellado',
  'food.chicken_liver': 'Hígado de pollo, cocido',
  'food.eggs_two_large': 'Dos huevos grandes',
  'food.tofu_firm': 'Tofu firme',
  'food.tofu_silken': 'Tofu sedoso',
  'food.tempeh': 'Tempeh',
  'food.seitan': 'Seitán',
  'food.edamame': 'Edamame pelado, cocido',
  'food.soy_curls': 'Tiras de soya, rehidratadas',
  'food.textured_vegetable_protein': 'Proteína vegetal texturizada',
  'food.black_bean_burger': 'Hamburguesa vegetal de frijoles negros',
  'food.pea_protein_isolate': 'Aislado de proteína de guisante',
  'food.soy_protein_isolate': 'Aislado de proteína de soya',
  'food.lentil_pasta': 'Pasta de lentejas rojas, cocida',
  'food.chickpea_pasta': 'Pasta de garbanzos, cocida',
  'food.soy_milk_unsweet': 'Leche de soya sin azúcar',
  'food.pea_milk_unsweet': 'Leche de guisante sin azúcar',
  'food.natto': 'Natto',
  'food.veggie_ground_soy': 'Soya molida sin carne',
  'food.falafel': 'Falafel al horno',
  'food.hemp_tofu': 'Tofu de cáñamo',
  'food.lupini_beans': 'Altramuces, cocidos',
  'food.mycoprotein': 'Trozos de micoproteína',
  'food.soy_yogurt_plain': 'Yogur de soya natural sin azúcar',
  'food.roasted_edamame': 'Edamame tostado',
  'food.oats_rolled': 'Avena en hojuelas, seca',
  'food.steel_cut_oats': 'Avena cortada, seca',
  'food.brown_rice': 'Arroz integral, cocido',
  'food.white_rice': 'Arroz blanco, cocido',
  'food.basmati_rice': 'Arroz basmati, cocido',
  'food.jasmine_rice': 'Arroz jazmín, cocido',
  'food.wild_rice': 'Arroz salvaje, cocido',
  'food.quinoa': 'Quinua, cocida',
  'food.barley': 'Cebada perlada, cocida',
  'food.bulgur': 'Bulgur, cocido',
  'food.farro': 'Farro, cocido',
  'food.buckwheat': 'Trigo sarraceno, cocido',
  'food.millet': 'Mijo, cocido',
  'food.amaranth': 'Amaranto, cocido',
  'food.sorghum': 'Sorgo, cocido',
  'food.whole_wheat_bread': 'Pan integral',
  'food.sourdough_bread': 'Pan de masa madre',
  'food.rye_bread': 'Pan de centeno',
  'food.whole_wheat_pasta': 'Pasta integral, cocida',
  'food.brown_rice_pasta': 'Pasta de arroz integral, cocida',
  'food.corn_tortilla': 'Tortilla de maíz',
  'food.whole_wheat_tortilla': 'Tortilla integral',
  'food.oat_bran': 'Salvado de avena, seco',
  'food.polenta': 'Polenta, cocida',
  'food.couscous_whole': 'Cuscús integral, cocido',
  'food.rice_cakes': 'Tortitas de arroz integral',
  'food.shredded_wheat': 'Cereal de trigo triturado',
  'food.muesli': 'Muesli integral sin azúcar añadida',
  'food.popcorn_air': 'Palomitas de maíz hechas con aire',
  'food.ezekiel_bread': 'Pan de granos germinados',
  'food.lentils_brown': 'Lentejas pardinas, cocidas',
  'food.lentils_red': 'Lentejas rojas, cocidas',
  'food.lentils_green': 'Lentejas verdes, cocidas',
  'food.chickpeas': 'Garbanzos, cocidos',
  'food.black_beans': 'Frijoles negros, cocidos',
  'food.kidney_beans': 'Frijoles rojos, cocidos',
  'food.pinto_beans': 'Frijoles pintos, cocidos',
  'food.navy_beans': 'Frijoles blancos pequeños, cocidos',
  'food.cannellini_beans': 'Frijoles cannellini, cocidos',
  'food.great_northern_beans': 'Frijoles blancos grandes, cocidos',
  'food.lima_beans': 'Habas de Lima, cocidas',
  'food.split_peas': 'Guisantes partidos, cocidos',
  'food.green_peas': 'Guisantes verdes, cocidos',
  'food.black_eyed_peas': 'Frijoles de carita, cocidos',
  'food.mung_beans': 'Frijoles mungo, cocidos',
  'food.adzuki_beans': 'Frijoles adzuki, cocidos',
  'food.fava_beans': 'Habas, cocidas',
  'food.hummus': 'Hummus',
  'food.refried_beans_nonfat': 'Frijoles refritos sin grasa',
  'food.soybeans': 'Frijoles de soya, cocidos',
  'food.broccoli': 'Brócoli, cocido',
  'food.spinach': 'Espinaca, cocida',
  'food.kale': 'Col rizada, cocida',
  'food.cauliflower': 'Coliflor, cocida',
  'food.brussels_sprouts': 'Coles de Bruselas, cocidas',
  'food.asparagus': 'Espárragos, cocidos',
  'food.green_beans': 'Judías verdes, cocidas',
  'food.zucchini': 'Calabacín, cocido',
  'food.bell_pepper_red': 'Pimiento rojo',
  'food.carrots': 'Zanahorias, cocidas',
  'food.tomato': 'Tomate crudo',
  'food.cucumber': 'Pepino crudo',
  'food.lettuce_romaine': 'Lechuga romana',
  'food.cabbage': 'Repollo, cocido',
  'food.mushrooms': 'Champiñones blancos, cocidos',
  'food.onion': 'Cebolla cruda',
  'food.sweet_potato': 'Batata al horno',
  'food.potato_baked': 'Papa al horno con piel',
  'food.butternut_squash': 'Calabaza moscada, cocida',
  'food.beets': 'Remolacha, cocida',
  'food.eggplant': 'Berenjena, cocida',
  'food.celery': 'Apio crudo',
  'food.bok_choy': 'Bok choy, cocido',
  'food.swiss_chard': 'Acelga, cocida',
  'food.collard_greens': 'Hojas de berza, cocidas',
  'food.artichoke': 'Alcachofa, cocida',
  'food.okra': 'Quimbombó, cocido',
  'food.snap_peas': 'Guisantes dulces',
  'food.corn': 'Maíz dulce, cocido',
  'food.snow_peas': 'Tirabeques crudos',
  'food.pumpkin': 'Calabaza, cocida',
  'food.spaghetti_squash': 'Calabaza espagueti, cocida',
  'food.turnip': 'Nabo, cocido',
  'food.parsnip': 'Chirivía, cocida',
  'food.radish': 'Rábano crudo',
  'food.arugula': 'Rúcula cruda',
  'food.watercress': 'Berro crudo',
  'food.leeks': 'Puerros crudos',
  'food.fennel': 'Bulbo de hinojo crudo',
  'food.kohlrabi': 'Colinabo, cocido',
  'food.acorn_squash': 'Calabaza bellota, cocida',
  'food.bell_pepper_green': 'Pimiento verde',
  'food.cherry_tomatoes': 'Tomates cherry',
  'food.mixed_greens': 'Mezcla de hojas verdes',
  'food.sauerkraut': 'Chucrut',
  'food.portobello': 'Champiñón portobello a la parrilla',
  'food.spinach_raw': 'Espinaca cruda',
  'food.broccolini': 'Broccolini, cocido',
  'food.jicama': 'Jícama cruda',
  'food.tomatillo': 'Tomatillo crudo',
  'food.apple': 'Manzana con piel',
  'food.banana': 'Banano',
  'food.orange': 'Naranja',
  'food.strawberries': 'Fresas',
  'food.blueberries': 'Arándanos azules',
  'food.raspberries': 'Frambuesas',
  'food.blackberries': 'Moras',
  'food.grapes': 'Uvas',
  'food.pineapple': 'Piña',
  'food.mango': 'Mango',
  'food.watermelon': 'Sandía',
  'food.cantaloupe': 'Melón cantalupo',
  'food.peach': 'Melocotón',
  'food.pear': 'Pera con piel',
  'food.plum': 'Ciruela',
  'food.kiwi': 'Kiwi',
  'food.cherries': 'Cerezas',
  'food.grapefruit': 'Toronja',
  'food.pomegranate': 'Semillas de granada',
  'food.avocado_fruit': 'Aguacate',
  'food.dates': 'Dátiles Medjool',
  'food.figs_dried': 'Higos secos',
  'food.raisins': 'Pasas',
  'food.apricot': 'Albaricoques',
  'food.clementine': 'Clementina',
  'food.honeydew': 'Melón verde',
  'food.papaya': 'Papaya',
  'food.nectarine': 'Nectarina',
  'food.cranberries_dried': 'Arándanos rojos secos sin azúcar',
  'food.guava': 'Guayaba',
  'food.passion_fruit': 'Maracuyá',
  'food.lychee': 'Lichi',
  'food.starfruit': 'Carambola',
  'food.dragon_fruit': 'Pitahaya',
  'food.greek_yogurt_nonfat': 'Yogur griego natural sin grasa',
  'food.greek_yogurt_2pct': 'Yogur griego natural, 2 %',
  'food.skyr': 'Skyr natural',
  'food.cottage_cheese_lowfat': 'Queso cottage bajo en grasa',
  'food.milk_skim': 'Leche descremada',
  'food.milk_1pct': 'Leche, 1 %',
  'food.milk_2pct': 'Leche, 2 %',
  'food.yogurt_plain_lowfat': 'Yogur natural bajo en grasa',
  'food.kefir_plain': 'Kéfir natural bajo en grasa',
  'food.cheddar': 'Queso cheddar',
  'food.mozzarella_part_skim': 'Mozzarella semidescremada',
  'food.parmesan': 'Queso parmesano',
  'food.feta': 'Queso feta',
  'food.swiss_cheese': 'Queso suizo',
  'food.ricotta_part_skim': 'Ricotta semidescremada',
  'food.string_cheese': 'Queso en tiras semidescremado',
  'food.cream_cheese_light': 'Queso crema ligero',
  'food.almond_milk_unsweet': 'Leche de almendras sin azúcar',
  'food.oat_milk_unsweet': 'Leche de avena sin azúcar',
  'food.coconut_milk_beverage': 'Bebida de leche de coco sin azúcar',
  'food.cashew_milk_unsweet': 'Leche de anacardos sin azúcar',
  'food.greek_yogurt_whole': 'Yogur griego natural de leche entera',
  'food.buttermilk_lowfat': 'Suero de leche bajo en grasa',
  'food.goat_cheese': 'Queso de cabra suave',
  'food.cottage_cheese_nonfat': 'Queso cottage sin grasa',
  'food.provolone': 'Queso provolone',
  'food.almonds': 'Almendras',
  'food.walnuts': 'Nueces',
  'food.cashews': 'Anacardos',
  'food.pistachios': 'Pistachos',
  'food.pecans': 'Nueces pecanas',
  'food.hazelnuts': 'Avellanas',
  'food.brazil_nuts': 'Nueces de Brasil',
  'food.macadamia': 'Nueces de macadamia',
  'food.peanuts': 'Maní tostado',
  'food.peanut_butter': 'Mantequilla de maní natural',
  'food.almond_butter': 'Mantequilla de almendras natural',
  'food.chia_seeds': 'Semillas de chía',
  'food.flax_seeds': 'Linaza molida',
  'food.pumpkin_seeds': 'Semillas de calabaza',
  'food.sunflower_seeds': 'Semillas de girasol',
  'food.sesame_seeds': 'Semillas de sésamo',
  'food.hemp_seeds': 'Semillas de cáñamo',
  'food.tahini': 'Tahini',
  'food.cashew_butter': 'Mantequilla de anacardos',
  'food.pine_nuts': 'Piñones',
  'food.mixed_nuts': 'Mezcla de frutos secos sin sal',
  'food.sunflower_butter': 'Mantequilla de semillas de girasol',
  'food.roasted_chickpeas': 'Garbanzos tostados',
  'food.pepitas': 'Pepitas de calabaza',
  'food.poppy_seeds': 'Semillas de amapola',
  'food.coconut_flakes': 'Hojuelas de coco sin azúcar',
  'food.olive_oil': 'Aceite de oliva extra virgen',
  'food.avocado_oil': 'Aceite de aguacate',
  'food.canola_oil': 'Aceite de canola',
  'food.flaxseed_oil': 'Aceite de linaza',
  'food.walnut_oil': 'Aceite de nuez',
  'food.sesame_oil': 'Aceite de sésamo',
  'food.avocado_half': 'Medio aguacate',
  'food.olives_black': 'Aceitunas negras',
  'food.olives_green': 'Aceitunas verdes',
  'food.guacamole': 'Guacamole',
  'food.coconut_oil': 'Aceite de coco',
  'food.butter': 'Mantequilla',
  'food.ghee': 'Ghee',
  'food.mct_oil': 'Aceite MCT',
  'food.green_tea': 'Té verde sin azúcar',
  'food.black_coffee': 'Café negro',
  'food.herbal_tea': 'Té de hierbas sin azúcar',
  'food.sparkling_water': 'Agua con gas sin azúcar',
  'food.tomato_juice_lowsodium': 'Jugo de tomate bajo en sodio',
  'food.orange_juice': 'Jugo de naranja 100 %',
  'food.vegetable_juice_lowsodium': 'Jugo de vegetales bajo en sodio',
  'food.coconut_water': 'Agua de coco sin azúcar',
  'food.protein_shake_water': 'Batido de proteína de suero con agua',
  'food.vegan_protein_shake': 'Batido de proteína vegetal con agua',
  'food.matcha_unsweet': 'Matcha sin azúcar',
  'food.kombucha_unsweet': 'Kombucha baja en azúcar',
  'food.mustard': 'Mostaza amarilla',
  'food.salsa': 'Salsa de tomate',
  'food.balsamic_vinegar': 'Vinagre balsámico',
  'food.hot_sauce': 'Salsa picante',
  'food.soy_sauce_low_sodium': 'Salsa de soya baja en sodio',
  'food.pesto': 'Pesto de albahaca',
  'food.nutritional_yeast': 'Levadura nutricional',
  'food.tomato_paste': 'Pasta de tomate sin sal añadida',
  'food.apple_cider_vinegar': 'Vinagre de sidra de manzana',
  'food.lemon_juice': 'Jugo de limón fresco',
  'food.garlic': 'Ajo crudo',
  'food.ginger': 'Jengibre fresco rallado',
  'food.greek_yogurt_dressing': 'Aderezo de yogur griego con hierbas',
  'food.tzatziki': 'Tzatziki',
  'food.overnight_oats': 'Avena remojada (avena, leche y frutos rojos)',
  'food.greek_yogurt_berry_bowl': 'Tazón de yogur griego con frutos rojos',
  'food.chicken_rice_veg_bowl': 'Tazón de pollo, arroz y vegetales',
  'food.tofu_stir_fry': 'Salteado de tofu y vegetales',
  'food.lentil_soup': 'Sopa de lentejas y vegetales',
  'food.turkey_chili': 'Chili de pavo y frijoles',
  'food.salmon_quinoa_bowl': 'Tazón de salmón y quinua',
  'food.veggie_burrito_bowl': 'Tazón de burrito con frijoles y vegetales',
  'food.egg_veggie_scramble': 'Huevos revueltos con vegetales',
  'food.tuna_salad_greens': 'Ensalada de atún sobre hojas verdes',
};
